from modules.ingredients import Ingredient
from constants import *

# Create a bread recipe
recipes = {
    "peasant bread": {
        "preheat": "preheat oven",
        "preheatTemp": 425,
        "yields":1,
        "yieldUnit":"loaf",
        "yieldConversions": 
            {"loaf": 1, 
             "slice": 14
             },
        "servings":14,
        "servingUnit":"slice",
        "category":"bread",
        "subcategory":"lean white",
        "kosher": "pareve",
        "notes":"This is a basic white bread recipe",
        "tags": ["bread", "white bread", "lean bread", "french bread"],
        "ingredients": [Ingredient("ap flour", 454), Ingredient("salt", 10), Ingredient("water", 320), Ingredient("instant dry yeast", 4)],
        "steps": [
            "If you are conserned about your yeast or need to speed up the process, proof the yeast in the water with a pinch of sugar. Skip otherwise", 
            "Combine the dry ingredients in a large bowl or bowl mixer bowl", 
            "Add 3/4 of the water and mix until a shaggy dough forms. If the dough is too dry, add more water. If the dough is too wet, add more flour", 
            "Knead the dough until it is smooth and elastic. This can take 10-15 minutes by hand or 5-7 minutes in a mixer",
            "Place the dough in a greased bowl and cover with a towel. Let rise until doubled in size, about 1 - 1.5 hours",
            "Punch down the dough and shape into a loaf. Place in a greased loaf pan and let rise until doubled in size, about 1 hour",
            "Bake at 425 for 25-30 minutes or until the internal temperature reaches 190F or nice golden crust has formed and sounds hollow when you knock the bottom.",
            "Let cool for at least 30 minutes before slicing"
        ]
    },


    'challah' : {
        "preheat": "preheat oven",
        "preheatTemp": 350,
        "yields":2,
        "yieldUnit":"loaf",
        "servings":20,
        "servingUnit":"slice",
        "category":"bread",
        "subcategory":"enriched white",
        "notes":"This is a basic challah recipe perefct for Shabbat",
        "tags": ["bread", "white bread", "enriched bread", "egg bread"],
        "kosher": "pareve",
        "ingredients": [
            Ingredient("ap flour", 4, qtyUnit='cup'), 
            Ingredient("salt", 2, qtyUnit='tsp'), 
            Ingredient("water", 1, qtyUnit='cup'), 
            Ingredient("instant dry yeast", 2, qtyUnit='tsp'), 
            Ingredient("sugar", 0.25, qtyUnit='cup'), 
            Ingredient("lg egg", 3), 
            Ingredient("olive oil", 0.25, qtyUnit='cup'),
            ],
        "steps": [
            "If you are conserned about your yeast or need to speed up the process, proof the yeast in the water with a pinch of sugar. Skip otherwise",
            "Combine the dry ingredients in a large bowl or bowl mixer bowl",
            "Combine the wet ingredients in a separate bowl reserving 1/4 of the water, reserve the egg white for the egg wash",
            "Add the wet ingredients to the dry ingredients and mix until a shaggy dough forms. Add the remaining water if the dough is too dry",
            "Will be a little tackier than a bread dough. Knead the dough until it is smooth and elastic. This can take 10-15 minutes by hand or 5-7 minutes in a mixer. ",
            "Place the dough in a greased bowl and cover with a towel. Let rise until doubled in size, about 1 - 1.5 hours",
            "Make the egg wash by adding a little water to the reserved egg white and beating with a small whisk or fork",
            "After dough has doubled, punch down the dough and divide by 2. Cut each half into 3 even pieces and roll into ropes. Braid the ropes and place in a greased loaf pan. Let rise until doubled in size, about 1 hour",
            "Brush with an egg wash and bake at 350 for 25-30 minutes or until the internal temperature reaches 190F or nice golden crust has formed and sounds hollow when you knock the bottom.",
            "Let cool for at least 30 minutes before slicing"
        ]
    },


## Instant coffee
    "instant coffee" : {
        "preheat": 'Boil water',
        "preheatTemp": 212,
        "yields":1,
        "yieldUnit":"cup",
        "servings":1,
        "servingUnit":"cup",
        "category":"beverage",
        "subcategory":"coffee",
        "notes":"This is a basic instant coffee recipe",
        "tags": ["beverage", "coffee", "instant coffee"],
        "kosher": "pareve",
        "ingredients": [
            Ingredient("instant coffee", 2, qtyUnit='tsp'),
            Ingredient("sugar", 1, qtyUnit='tsp'),
            Ingredient("water", 250, qtyUnit='ml'),
        ],
        "steps": [
            "Boil the water or take hot water from a kettle",
            "On Shabbat, use a keli shelishi (a “third vessel”) to pour the water into another cup",
            "Pour the water either from the kettle or the keli shelishi into the final cup",
            "Add the instant coffee and sugar to a cup",
            "Stir until the coffee and sugar are dissolved"
        ],
    },
    "french press coffee" : {
        "preheat":'boil water',
        "preheatTemp": 212,
        "servings":4,
        "servingUnit":"cup",
        "category":"beverage",
        "subcategory":"coffee",
        "notes":"This is a basic french press coffee recipe",
        "tags": ["beverage", "coffee", "french press"],
        "kosher": "pareve",
        "ingredients": [
            Ingredient("whole coffee bean", 0.5, qtyUnit='cup'),
            Ingredient("water", 4, qtyUnit='cup'),
        ],
        "steps": [
            "Start to boil the water",
            "Grind the coffee beans to an even coarse grind",
            "Add the coffee beans to the french press",
            "When the water reaches a boil, remove from heat and let sit for 30 seconds",
            "Bloom the coffee by adding a small amount of water to the coffee and letting it sit for 30 seconds",
            "Add the rest of the water and let sit for 6-7 minutes",
            "Press the coffee and pour into a cup"
        ],
    },
    "white rice" : {
        "preheat":"bring water to boil in a large pot ",
        "preheatTemp": 212,
        "servings":4,
        "servingUnit":"cup",
        "category":"grain",
        "subcategory":"rice",
        "notes":"This is a basic white rice recipe",
        "tags": ["grain", "rice", "white rice"],
        "kosher": "pareve",
        "ingredients": [
            Ingredient("white rice", 1, qtyUnit='cup'),
            Ingredient("water", 2, qtyUnit='cup'),
        ],
        "steps": [
            "Rinse the rice until the water runs clear",
            "Add the rice and water to a pot",
            "Bring the water to a boil",
            "Reduce the heat to low and cover",
            "Cook for 15-20 minutes",
            "Fluff the rice with a fork"
        ],
    },
    "popcorn" : {
        "preheat": 'stove top medium heat or air popper',
        "preheatTemp": None,
        "servings":4,
        "servingUnit":"cup",
        "category":"grain",
        "subcategory":"popcorn",
        "notes":"This is a basic popcorn recipe",
        "tags": ["grain", "popcorn"],
        "kosher": "pareve",
        "ingredients": [
            Ingredient("popcorn kernels", 0.25, qtyUnit='cup'),
            Ingredient("grapeseed oil", 1, qtyUnit='tbsp'),
            Ingredient("salt", 1, qtyUnit='tbsp'), 
            Ingredient("nutritional yeast", 1, qtyUnit='tbsp'),
        ],
        "steps": [
            "Add the oil to a pot and heat over medium heat",
            "Add the popcorn kernels and cover",
            "Shake the pot occasionally",
            "When the popping slows, remove from heat",
            "Season with oil, salt, nutritional yeast and any other seasonings"
        ],
    },
    "fried egg" : {
        "preheat": 'stove top medium heat',
        "preheatTemp": None,
        "servings":1,
        "servingUnit":"egg",
        "category":"protein",
        "subcategory":"egg",
        "notes":"This is a basic fried egg recipe",
        "tags": ["protein", "egg", "fried egg"],
        "kosher": "pareve",
        "ingredients": [
            Ingredient("lg egg", 1),
            Ingredient("grapeseed oil", 1, qtyUnit='tsp'),
            Ingredient("salt", 1, qtyUnit='tsp'), 
        ],
        "steps": [
            "Heat the oil in a pan over medium heat",
            "Crack the egg into the pan",
            "Season with salt and pepper",
            "Cook until the white is set and the yolk is runny, flip for over easy any more is too much",
        ],
    }, 
    "scrambled eggs" : {
        "preheat": 'stove top medium heat',
        "preheatTemp": None,
        "servings":2,
        "servingUnit":"egg",
        "category":"protein",
        "subcategory":"egg",
        "notes":"This is a basic scrambled egg recipe",
        "tags": ["protein", "egg", "scrambled egg"],
        "kosher": "pareve",
        "ingredients": [
            Ingredient("lg egg", 2),
            Ingredient("water", 1, qtyUnit='tbsp'),
            Ingredient("grapeseed oil", 2, qtyUnit='tsp'),
            Ingredient("salt", 1, qtyUnit='tsp'), 
        ],
        "steps": [
            "Heat the oil in a pan over medium heat",
            "Crack the eggs into a bowl and add salt to taste",
            "Whisk the eggs until the yolks are broken and the eggs are uniform",
            "Whisk in half of the oil and the water, this will make the eggs fluffy and light yet creamy",
            "Add the eggs to the pan and let sit for 30 seconds",
            "Season with salt and pepper",
            "You can stir the eggs often for small curds or let sit for larger curds",
            "Cook until the eggs are set",]
    },
    "roux" : {
        "preheat": 'stove top medium heat',
        "preheatTemp": None,
        "servings":1,
        "servingUnit":"cup",
        "category":"sauce",
        "subcategory":"roux",
        "notes":"3:2 ratio of flour to oil",
        "tags": ["sauce", "roux"],
        "kosher": "pareve",
        "ingredients": [
            Ingredient("ap flour", (CUP/5)*3),
            Ingredient("grapeseed oil", (CUP/5)*2, qtyUnit='g'),
        ],
        "steps": [
            "Heat the oil in a pan over medium heat",
            "Add the flour and whisk until a smooth paste forms",
            "Cook for 2-3 minutes until the flour is cooked",
            "Use in sauces to thicken",
        ],
    },
    "mirepoix" : {
        "preheat": None,
        "preheatTemp": None,
        "yields":400,
        "yieldUnit":"g",
        "yieldConversions": {
        },
        "servings":400 / 75, # serving size is 75 grams
        "servingUnit":"each",
        "servingConversions": {
            'g': 1/75
        },
        "category":"mise en place",
        "subcategory":"mirepoix",
        "notes":"2:1:1 ratio of onion, carrot, celery",
        "tags": ["sauce", "mirepoix"],
        "kosher": "pareve",
        "ingredients": [
            Ingredient("onion", 200, qtyUnit='g'),
            Ingredient("carrot", 100),
            Ingredient("celery", 100),
        ],
        "steps": [
            "Heat the oil in a pan over medium heat",
            "Add the onion and cook until translucent",
            "Add the carrot and celery and cook until soft",
            "Season with salt and pepper",
            "Use in sauces to add flavor",
        ],
    },
    "fresh tomato sauce" : {
        "preheat": 'stove top medium heat',
        "preheatTemp": None,
        "yields":2.42,
        "yieldUnit":"l",
        "servings":2420/CUP,
        "servingUnit":"cup",
        "category":"sauce",
        "subcategory":"tomato",
        "notes":"This is a basic tomato sauce recipe",
        "tags": ["sauce", "tomato sauce"],
        "kosher": "pareve",
        "ingredients": [
            Ingredient("olive oil", 40, qtyUnit='ml'),
            Ingredient("onion", 113, qtyUnit='g'),
            Ingredient("garlic", 30, qtyUnit='g'),
            Ingredient("plum tomato", 2.25, qtyUnit='kg'),
            Ingredient("basil", 42, qtyUnit='g'),
            Ingredient("salt", 2, qtyUnit='tsp'),
        ],
        "steps": [
            "Heat the oil in a pan over medium heat",
            "Add the onion and cook until they get a light colour, 12-15 minutes",
            "Add the garlic and cook until fragrant, about 1 minute",
            "Add the tomatoes and salt",
            "Bring to simmer and cook over low heat for 30-45 minutes depending on the tomatoes, stirring occasionally",
            "Add the basil and simmer for 5 more minutes",
            "Season with salt and pepper",
            "Blitz if you want a finer texture",
        ],
    },
    "canned tomato sauce" : {
        "preheat": 'stove top medium heat',
        "preheatTemp": None,
        "yields":2.42,
        "yieldUnit":"l",
        "servings":2420/CUP,
        "servingUnit":"cup",
        "category":"sauce",
        "subcategory":"tomato",
        "notes":"This is a basic canned tomato sauce recipe",
        "tags": ["sauce", "tomato sauce"],
        "kosher": "pareve",
        "ingredients": [
            Ingredient("olive oil", 40, qtyUnit='ml'),
            Ingredient("onion", 113, qtyUnit='g'),
            Ingredient("garlic", 30, qtyUnit='g'),
            Ingredient("canned plum tomato", 2.02, qtyUnit='kg'),
            Ingredient("basil", 42, qtyUnit='g'),
            Ingredient("salt", 2, qtyUnit='tsp'),
        ],
        "steps": [
            "Heat the oil in a pan over medium heat",
            "Add the onion and cook until they get a light colour, 12-15 minutes",
            "Add the garlic and cook until fragrant, about 1 minute",
            "Add the tomatoes and salt",
            "Bring to simmer and cook over low heat for 30-45 minutes depending on the tomatoes, stirring occasionally",
            "Add the basil and simmer for 5 more minutes",
            "Season with salt and pepper",
            "Blitz if you want a finer texture",
        ],
    },
    "pesto": {
        "preheat": None,
        "preheatTemp": None,
        "yields":960,
        "yieldUnit":"ml",
        "servings":960/CUP,
        "servingUnit":"cup",
        "category":"sauce",
        "subcategory":"pesto",
        "tags": ["sauce", "pesto"],
        "kosher": "pareve",
        "ingredients": [
            Ingredient("basil", 227, qtyUnit='g'),
            Ingredient("walnut pieces", 284, qtyUnit='g'),
            Ingredient("garlic", 28, qtyUnit='g'),
            Ingredient("grapeseed oil", 300, qtyUnit='ml'),
            Ingredient("olive oil", 30, qtyUnit='ml'),
            Ingredient("salt", 1, qtyUnit='tbsp'),
        ],
        "steps": [
            "If the walnuts are not toasted you can toast them for a richer flavor",
            "Add the basil, garlic, walnuts nuts, and salt to a food processor",
            "Pulse until a paste forms",
            "Add the olive oil, then add grapeseed oil and pulse until smooth",
            "Adjust seasoning with salt and pepper",
        ],
    },
    "lemon juice": {
        "preheat": None,
        "preheatTemp": None,
        "yields":30,
        "yieldUnit":"ml",
        "servings":30/ML,
        "servingUnit":"ml",
        "category":"sauce",
        "subcategory":"lemon",
        "tags": ["sauce", "lemon juice"],
        "kosher": "pareve",
        "ingredients": [
            Ingredient("lemon", 1),
        ],
        "steps": [
            "Roll the lemon on the counter to break up the pulp",
            "Cut the lemon in half",
            "Squeeze the juice out of the lemon",
            "Strain the juice to remove seeds and pulp",
        ],
    },
        "scrap vegetable stock" : {
        "preheat": 'stove top medium heat',
        "preheatTemp": None,
        "yields":3.84,
        "yieldUnit":"l",
        "servings":3840/CUP,
        "servingUnit":"cup",
        "category":"stock",
        "subcategory":"vegetable",
        "notes":"",
        "tags": ["stock", "vegetable"],
        "kosher": "pareve",
        "ingredients": [
            Ingredient("grapeseed oil", 60, qtyUnit='ml'),
            Ingredient("stock scraps", 2, qtyUnit='kg'),
            Ingredient("onion", 2, qtyUnit='each'),
            Ingredient("carrot", 2, qtyUnit='each'),
            Ingredient("celery", 2, qtyUnit='each'),
            Ingredient("garlic", 1, qtyUnit='each'),
            Ingredient("jalapeno", 1),
            Ingredient("salt", 2, qtyUnit='tsp'),
            Ingredient("water", 4.8, qtyUnit='l'),
        ],
        "steps": [
            "Rough chop the vegetables",
            "Add the vegetables to a pot with the oil and saute until soft",
            "Add the water and salt",
            "Bring to a boil and simmer for 1 hour",
            "Strain the stock and discard the vegetables",
        ],
    },
    "gapacho" : {
        "preheat": None,
        "preheatTemp": None,
        "yields":1.9,
        "yieldUnit":"l",
        "servings":1900/CUP,
        "servingUnit":"cup",
        "category":"soup",
        "subcategory":"gazpacho",
        "notes":"",
        "tags": ["soup", "gazpacho"],
        "kosher": "pareve",
        "ingredients": [
            Ingredient("plum tomato", 1.8, qtyUnit='kg'),
            Ingredient("cucumber", 225, qtyUnit='g'),
            Ingredient("bell pepper", 225, qtyUnit='g'),
            Ingredient("jalapeno", 1),
            Ingredient("garlic", 4, qtyUnit='clove'),
            Ingredient("red wine vinegar", 140, qtyUnit='ml'),
            Ingredient("olive oil", 240, qtyUnit='ml'),
            Ingredient("salt", 2, qtyUnit='tsp'),
        ],
        "steps": [
            "Dice the vegetables",
            "Combine all the ingredients, cover and refrigerate overnight",
            "Puree the ingredients until smooth",
            "Season with salt and pepper",
            "Serve cold",
        ],
    },
    "garam masala" : {
        "preheat": None,
        "preheatTemp": None,
        "yields":57,
        "yieldUnit":"g",
        "servings":57,
        "servingUnit":"g",
        "category":"spice",
        "subcategory":"garam masala",
        "notes":"",
        "tags": ["spice", "garam masala"],
        "kosher": "pareve",
        "ingredients": [
            Ingredient("cardamom", 3, qtyUnit='g'),
            Ingredient("coriander", 7, qtyUnit='g'),
            Ingredient("cumin", 8, qtyUnit='g'),
            Ingredient("cinnamon", 1.25, qtyUnit='stick'),
            Ingredient("cloves", 2, qtyUnit='g'),
            Ingredient("black pepper", 5, qtyUnit='g'),
            Ingredient("nutmeg", 0.5, qtyUnit='g'),
            Ingredient("bay leaf", 2, qtyUnit='each'),
        ],
        "steps": [
            "Toast the spices in a dry pan until fragrant",
            "Grind the spices in a spice grinder",
            "Store in an airtight container",
        ],
    },
    "lime juice" : {
        "preheat": None,
        "preheatTemp": None,
        "yields":30,
        "yieldUnit":"ml",
        "servings":30/ML,
        "servingUnit":"ml",
        "category":"sauce",
        "subcategory":"lime",
        "tags": ["sauce", "lime juice"],
        "kosher": "pareve",
        "ingredients": [
            Ingredient("lime", 1),
        ],
        "steps": [
            "Roll the lime on the counter to break up the pulp",
            "Cut the lime in half",
            "Squeeze the juice out of the lime",
            "Strain the juice to remove seeds and pulp",
        ],
    },
    "falafel": {
        "preheat": 'on stovetop heat oil',
        "preheatTemp": 350,
        "yields":10,
        "yieldUnit":"each",
        "servings":10,
        "servingUnit":"each",
        "category":"protein",
        "subcategory":"falafel",
        "notes":"",
        "tags": ["protein", "falafel"],
        "kosher": "pareve",
        "ingredients": [
            Ingredient("dried chickpeas", 312, qtyUnit='g'),
            Ingredient("dried fava beans", 312, qtyUnit='g'),
            Ingredient("parsley", 1, qtyUnit='bunch'),
            Ingredient("green onion", 3, qtyUnit='each'),
            Ingredient("cayenne powder", 2, qtyUnit='g'),
            Ingredient("cumin", 6, qtyUnit='g'),
            Ingredient("coriander", 2.5, qtyUnit='g'),
            Ingredient("garlic", 6, qtyUnit='clove'),
            Ingredient("baking powder", 3.75, qtyUnit='g'),
            Ingredient("salt", 15, qtyUnit='g'),
            Ingredient("vegetable oil", 960, qtyUnit='ml'),
        ],
        "steps": [
            "Soak the chickpeas overnight and the fava beans for 2 nights",
            "Rough dice the vegetables",
            "Add the chickpeas, vegetables, and spices to a food processor",
            "Pulse until a rough paste forms",
            "Form mixture into balls and flatten slightly",
            "Fry until golden brown, about 4 minutes",
            "Remove from oil and drain on a paper towel",
            "Season with salt and serve immediately",
        ],

    },
    "sachet of spices" : {
        "preheat": None,
        "preheatTemp": None,
        "yields":1,
        "yieldUnit":"each",
        "servings":1,
        "servingUnit":"each",
        "category":"spice",
        "subcategory":"sachet",
        "notes":"",
        "tags": ["spice", "sachet"],
        "kosher": "pareve",
        "ingredients": [
            Ingredient("bay leaf", 1),
            Ingredient("thyme", 1, qtyUnit='sprig'),
            Ingredient("parsley", 3, qtyUnit='sprig'),
            Ingredient("black pepper", 10, "g"),
            Ingredient("garlic", 1, qtyUnit='clove'),
        ],
        "steps": [
            "Place all the ingredients in a cheesecloth and tie with twine",
            "Add to soups and sauces for flavor",
        ],
    },

}