from modules.ingredients import Ingredient
from constants import *

# Create a bread recipe
recipes = {
    "peasant bread": {
        "preheat": "preheat the oven",
        "preheatTemp": 425,
        "preheatUnit": "F",
        "yields":1,
        "yieldUnit":"loaf",
        "yieldConversions": 
            {"loaf": 1, 
             "slice": 14
             },
        "servings":14,
        "servingUnit":"slice",
        "category":"bread",
        "subcategory":"white",
        "kosher": "pareve",

        "tags": ["white bread", "lean bread", "french bread"],
        "ingredients": [Ingredient("ap flour", 454), Ingredient("salt", 10), Ingredient("water", 320), Ingredient("instant dry yeast", 4)],
        "times": {"active": "10-15 minutes", "proof": "100-180 minutes", "bake": "25-40 minutes"},
        "steps": [
            "If you are concerned about your yeast or need to speed up the process, proof the yeast in the water with a pinch of sugar. Skip otherwise", 
            "Combine the dry ingredients in a large bowl or bowl mixer bowl", 
            "Add 3/4 of the water and mix until a shaggy dough forms. If the dough is too dry, add more water. If the dough is too wet, add more flour", 
            "Knead the dough until it is smooth and elastic. This can take 10-15 minutes by hand or 5-7 minutes in a mixer",
            "Place the dough in a greased bowl and cover with a towel. Let rise until doubled in size, about 1 - 1.5 hours",
            "Punch down the dough and shape into a loaf. Place in a greased loaf pan and let rise until doubled in size, about 1 hour",
            "Bake at 425 for 25-30 minutes or until the internal temperature reaches 190F or nice golden crust has formed and sounds hollow when you knock the bottom.",
            "Let cool for at least 30 minutes before slicing"
        ]
    },
    "egg yolk": {
        "yields":18,
        "yieldUnit":"g",
        "servings":1,
        "servingUnit":"each",
        "category":"mise en place",
        "subcategory":"egg and dairy",
        "tags": ["egg", "yolk", "egg yolk"],
        "kosher": "pareve",
        "ingredients": [
            Ingredient("lg egg", 1),
        ],
        "times": {"active": "2 minutes"},
        "steps": [
            "Get 2 bowls, one for the egg white and one for the yolk",
            "Crack the egg in half and pour the yolk back and forth between the two halves until the white is removed",
        ],},
    "instant coffee" : {
        "preheat": 'Boil water',
        "yields":1,
        "yieldUnit":"cup",
        "servings":1,
        "servingUnit":"cup",
        "category":"beverage",
        "subcategory":"coffee",
        "tags": ["coffee", "instant coffee", "shabbat"],
        "kosher": "pareve",
        "times": {"Water to boil": "5-10 minutes"},
        "ingredients": [
            Ingredient("instant coffee", 2, qtyUnit='tsp'),
            Ingredient("sugar", 1, qtyUnit='tsp'),
            Ingredient("water", 250, qtyUnit='ml'),
        ],
        "steps": [
            "Boil the water or take hot water from a kettle",
            "On Shabbat, use a keli shelishi (a “third vessel”) to pour the water into another cup",
            "Pour the water either from the kettle or the keli shelishi into the final cup",
            "Add the instant coffee and sugar to a cup",
            "Stir until the coffee and sugar are dissolved"
        ],
    },
    "french press coffee" : {
        "preheat":'boil water',
        "servings":4,
        "servingUnit":"cup",
        "category":"beverage",
        "subcategory":"coffee",
        "notes":"Requires a french press",
        "tags": ["beverage", "coffee", "french press"],
        "kosher": "pareve",
        "ingredients": [
            Ingredient("whole coffee bean", 0.5, qtyUnit='cup', prep="coarse grind"),
            Ingredient("water", 4, qtyUnit='cup'),
        ],
        "times": {"boil water": "5-10 minutes", "bloom": "30 seconds", "brew": "6-7 minutes"},
        "steps": [
            "Start to boil the water",
            "Grind the coffee beans to an even coarse grind",
            "Add the coffee beans to the french press",
            "When the water reaches a boil, remove from heat and let sit for 30 seconds",
            "Bloom the coffee by adding a small amount of water to the coffee and letting it sit for 30 seconds",
            "Add the rest of the water and let sit for 6-7 minutes",
            "Press the coffee and pour into a cup"
        ],
    },
    "white rice" : {
        "preheat":"bring water to boil in a large pot",
        "servings":4,
        "servingUnit":"cup",
        "category":"grain",
        "subcategory":"rice",
        "notes":"You can substitute other long grain white rice",
        "tags": ["white rice", "jasmine rice"],
        "kosher": "pareve",
        "ingredients": [
            Ingredient("white rice", 1, qtyUnit='cup', prep='rinsed'),
            Ingredient("water", 2, qtyUnit='cup'),
        ],
        "times": {"active": "5 minutes", "cook": "15-20 minutes", "rest": "5 minutes"},
        "steps": [
            "Bring the water to a boil",
            "Rinse the rice until the water runs clear",
            "Add the rice and water to a pot",
            "Reduce the heat to low and cover",
            "Cook for 15-20 minutes",
            "Fluff the rice with a fork"
        ],
    },
    "popcorn" : {
        "preheat": 'stove top medium heat or air popper',
        "servings":4,
        "servingUnit":"cup",
        "category":"snack",
        "subcategory":"popcorn",
        "tags": ["grain", "popcorn"],
        "kosher": "pareve",
        "ingredients": [
            Ingredient("popcorn kernels", 0.25, qtyUnit='cup'),
            Ingredient("grapeseed oil", 1, qtyUnit='tbsp'),
            Ingredient("salt", 1, qtyUnit='tbsp'), 
            Ingredient("nutritional yeast", 1, qtyUnit='tbsp'),
        ],
        "steps": [
            "Add the oil to a pot and heat over medium heat",
            "Add the popcorn kernels and cover",
            "Shake the pot occasionally",
            "When the popping slows, remove from heat",
            "Alternatively used an air popper and walk away",
            "Season with oil, salt, nutritional yeast and any other seasonings"
        ],
    },
    "fried egg" : {
        "preheat": 'stove top medium heat',
        "servings":1,
        "servingUnit":"egg",
        "category":"breakfast",
        "subcategory":"egg",
        "tags": ["protein", "egg", "fried egg"],
        "kosher": "pareve",
        "ingredients": [
            Ingredient("lg egg", 1),
            Ingredient("grapeseed oil", 1, qtyUnit='tsp'),
            Ingredient("salt", 1, qtyUnit='tsp'), 
        ],
        "times": {"cook": "2-5 minutes"},
        "steps": [
            "Heat the oil in a pan over medium heat",
            "Crack the egg into the pan",
            "Season with salt and pepper",
            "Cook until the white is set and the yolk is runny (2-5 minutes depending on temperature and desired doneness), flip for over easy",
        ],
    }, 
    "scrambled eggs" : {
        "preheat": 'stove top medium heat',
        "servings":2,
        "servingUnit":"egg",
        "category":"breakfast",
        "subcategory":"egg",
        "notes":"This is a basic scrambled egg recipe",
        "tags": ["protein", "egg", "scrambled egg"],
        "kosher": "pareve",
        "times": {"active": "7-10 minutes","cook": "3-7 minutes"},
        "ingredients": [
            Ingredient("lg egg", 2, prep="beaten"),
            Ingredient("water", 1, qtyUnit='tbsp'),
            Ingredient("grapeseed oil", 2, qtyUnit='tsp'),
            Ingredient("salt", 1, qtyUnit='tsp'), 
        ],
        "steps": [
            "Heat the oil in a pan over medium heat",
            "Crack the eggs into a bowl and add salt to taste",
            "Whisk the eggs until the yolks are broken and the eggs are uniform",
            "Whisk in half of the oil and the water, this will make the eggs fluffy and light yet creamy",
            "Add the eggs to the pan and let sit for 30 seconds",
            "Season with salt and pepper",
            "You can stir the eggs often for small curds or let sit for larger curds",
            "Cook until the eggs are set",]
    },
    "roux" : {
        "preheat": 'stove top medium heat',
        "servings":1,
        "servingUnit":"cup",
        "category":"mise en place",
        "subcategory":"sauces",
        "notes":"3:2 ratio of flour to oil",
        "tags": ["sauces", "roux"],
        "kosher": "pareve",
        "ingredients": [
            Ingredient("ap flour", (CUP/5)*3),
            Ingredient("grapeseed oil", (CUP/5)*2, qtyUnit='g'),
        ],
        "times": {"active": "5 minutes"},
        "steps": [
            "Heat the oil in a pan over medium heat",
            "Add the flour and whisk until a smooth paste forms",
            "Cook for 2-3 minutes until the flour is cooked",
            "Use in sauces to thicken",
        ],
    },
    "mirepoix" : {
        "yields":400,
        "yieldUnit":"g",
        "yieldConversions": {
        },
        "servings":400 / 75, # serving size is 75 grams
        "servingUnit":"each",
        "servingConversions": {
            'g': 1/75
        },
        "category":"mise en place",
        "subcategory":"vegetables",
        "notes":"2:1:1 ratio of onion, carrot, celery",
        "tags": ["vegetables", "mirepoix"],
        "kosher": "pareve",
        "ingredients": [
            Ingredient("onion", 200, qtyUnit='g'),
            Ingredient("carrot", 100),
            Ingredient("celery", 100),
        ],
        "times": {"active": "5-15 minutes"},
        "steps": [
            "Clean and dice the vegetables",
        ],
    },
    "fresh tomato sauce" : {
        "preheat": 'stove top medium heat',
        "yields":2.42,
        "yieldUnit":"l",
        "servings":2420/CUP,
        "servingUnit":"cup",
        "category":"sauces",
        "subcategory":"sauces",
        "notes":"This is a basic tomato sauce recipe and can be used as a base for other sauces",
        "tags": ["sauces", "tomato sauce"],
        "kosher": "pareve",
        "ingredients": [
            Ingredient("olive oil", 40, qtyUnit='ml'),
            Ingredient("onion", 113, qtyUnit='g', prep="diced"),
            Ingredient("garlic", 30, qtyUnit='g', prep="minced"),
            Ingredient("plum tomato", 2.25, qtyUnit='kg', prep="diced"),
            Ingredient("basil", 42, qtyUnit='g', prep="chopped"),
            Ingredient("salt", 2, qtyUnit='tsp'),
        ],
        "times": {"active": "10-20 minutes", "prep": "5-15 minutes", "cook": "50-75 minutes"},
        "steps": [
            "Heat the oil in a pan over medium heat",
            "Add the onion and cook until they get a light colour, 12-15 minutes",
            "Add the garlic and cook until fragrant, about 1 minute",
            "Add the tomatoes and salt",
            "Bring to simmer and cook over low heat for 30-45 minutes depending on the tomatoes, stirring occasionally",
            "Add the basil and simmer for 5 more minutes",
            "Season with salt and pepper",
            "Blitz if you want a finer texture",
        ],
    },
    "canned tomato sauce" : {
        "preheat": 'stove top medium heat',
        "yields":2.42,
        "yieldUnit":"l",
        "servings":2420/CUP,
        "servingUnit":"cup",
        "category":"sauces",
        "subcategory":"sauces",
        "notes":"This is a basic canned tomato sauce recipe",
        "tags": ["sauces", "tomato sauce"],
        "kosher": "pareve",
        "ingredients": [
            Ingredient("olive oil", 40, qtyUnit='ml'),
            Ingredient("onion", 113, qtyUnit='g', prep="diced"),
            Ingredient("garlic", 30, qtyUnit='g', prep="minced"),
            Ingredient("canned plum tomato", 2.02, qtyUnit='kg'),
            Ingredient("basil", 42, qtyUnit='g', prep="chopped"),
            Ingredient("salt", 2, qtyUnit='tsp'),
        ],
        "times": {"active": "5-15 minutes", "prep": "3-10 minutes", "cook": "50-75 minutes"},
        "steps": [
            "Heat the oil in a pan over medium heat",
            "Add the onion and cook until they get a light colour, 12-15 minutes",
            "Add the garlic and cook until fragrant, about 1 minute",
            "Add the tomatoes and salt",
            "Bring to simmer and cook over low heat for 30-45 minutes depending on the tomatoes, stirring occasionally",
            "Add the basil and simmer for 5 more minutes",
            "Season with salt and pepper",
            "Blitz if you want a finer texture",
        ],
    },
    "pesto": {
        "prepareAhead": "Toast the walnuts ahead of time",
        "yields":960,
        "yieldUnit":"ml",
        "servings":960/CUP,
        "servingUnit":"cup",
        "category":"sauces",
        "subcategory":"sauces",
        "tags": ["sauces", "pesto"],
        "kosher": "pareve",
        "ingredients": [
            Ingredient("basil", 227, qtyUnit='g'),
            Ingredient("walnut pieces", 284, qtyUnit='g', prep="toasted"),
            Ingredient("garlic", 28, qtyUnit='g'),
            Ingredient("grapeseed oil", 300, qtyUnit='ml'),
            Ingredient("olive oil", 30, qtyUnit='ml'),
            Ingredient("salt", 1, qtyUnit='tbsp'),
        ],
        "times": {"active": "5-10 minutes"},
        "steps": [
            "If the walnuts are not toasted you can toast them for a richer flavor",
            "Add the basil, garlic, walnuts nuts, and salt to a food processor",
            "Pulse until a paste forms",
            "Add the olive oil, then add grapeseed oil and pulse until smooth",
            "Adjust seasoning with salt and pepper",
        ],
    },
    "lemon juice": {
        "yields":30,
        "yieldUnit":"ml",
        "servings":30/ML,
        "servingUnit":"ml",
        "category":"mise en place",
        "subcategory":"liquids",
        "tags": ["lemon juice", "citrus"],
        "kosher": "pareve",
        "ingredients": [
            Ingredient("lemon", 1),
        ],
        "steps": [
            "Roll the lemon on the counter to break up the pulp",
            "Cut the lemon in half",
            "Squeeze the juice out of the lemon",
            "Strain the juice to remove seeds and pulp",
        ],
    },
    "vegetable stock" : {
        "preheat": 'stove top medium heat',
        "yields":3.84,
        "yieldUnit":"l",
        "servings":3840/CUP,
        "servingUnit":"cup",
        "category":"mise en place",
        "subcategory":"stock",
        "tags": ["stock", "vegetables"],
        "kosher": "pareve",
        "ingredients": [
            Ingredient("grapeseed oil", 60, qtyUnit='ml'),
            Ingredient("stock scraps", 2, qtyUnit='kg'),
            Ingredient("onion", 2, qtyUnit='each'),
            Ingredient("carrot", 2, qtyUnit='each'),
            Ingredient("celery", 2, qtyUnit='each'),
            Ingredient("garlic", 1, qtyUnit='each'),
            Ingredient("jalapeno", 1),
            Ingredient("salt", 2, qtyUnit='tsp'),
            Ingredient("water", 4.8, qtyUnit='l'),
        ],
        "times": {"active": "10-15 minutes", "cook": "60-120 minutes"},
        "steps": [
            "Rough chop the vegetables",
            "Add the vegetables to a pot with the oil and saute until soft",
            "Add the water and salt",
            "Bring to a boil and simmer for 1-2 hours or until reduced by half",
            "Strain the stock and discard the vegetables",
        ],
    },
    "gaspacho" : {
        "yields":1.9,
        "yieldUnit":"l",
        "servings":1900/CUP,
        "servingUnit":"cup",
        "category":"soup",
        "subcategory":"cold",
        "tags": ["soup", "gazpacho"],
        "kosher": "pareve",
        "ingredients": [
            Ingredient("plum tomato", 1.8, qtyUnit='kg', prep="diced"),
            Ingredient("cucumber", 225, qtyUnit='g', prep="diced"),
            Ingredient("bell pepper", 225, qtyUnit='g', prep="diced"),
            Ingredient("jalapeno", 1, prep="diced"),
            Ingredient("garlic", 4, qtyUnit='clove', prep="minced"),
            Ingredient("red wine vinegar", 140, qtyUnit='ml'),
            Ingredient("olive oil", 240, qtyUnit='ml'),
            Ingredient("salt", 2, qtyUnit='tsp'),
        ],
        "times": {"active": "10-15 minutes",  "chill": "10-24 hours"},
        "steps": [
            "Dice the vegetables",
            "Combine all the ingredients, cover and refrigerate overnight",
            "Puree the ingredients until smooth",
            "Season with salt and pepper",
            "Serve cold",
        ],
    },
    "garam masala" : {
        "yields":57,
        "yieldUnit":"g",
        "servings":57,
        "servingUnit":"g",
        "category":"mise en place",
        "subcategory":"herbs and spices",
        "tags": ["spice", "garam masala"],
        "kosher": "pareve",
        "ingredients": [
            Ingredient("cardamom", 3, qtyUnit='g'),
            Ingredient("coriander", 7, qtyUnit='g'),
            Ingredient("cumin", 8, qtyUnit='g'),
            Ingredient("cinnamon", 1.25, qtyUnit='stick'),
            Ingredient("cloves", 2, qtyUnit='g'),
            Ingredient("black pepper", 5, qtyUnit='g'),
            Ingredient("nutmeg", 0.5, qtyUnit='g'),
            Ingredient("bay leaf", 2, qtyUnit='each'),
        ],
        "times": {"active": "5-10 minutes"},
        "steps": [
            "Toast the spices in a dry pan until fragrant",
            "Grind the spices in a spice grinder",
            "Store in an airtight container",
        ],
    },
    "lime juice" : {
        "yields":30,
        "yieldUnit":"ml",
        "servings":30/ML,
        "servingUnit":"ml",
        "category":"mise en place",
        "subcategory":"liquids",
        "tags": ["sauces", "lime juice"],
        "kosher": "pareve",
        "ingredients": [
            Ingredient("lime", 1),
        ],
        "steps": [
            "Roll the lime on the counter to break up the pulp",
            "Cut the lime in half",
            "Squeeze the juice out of the lime",
            "Strain the juice to remove seeds and pulp",
        ],
    },
    "falafel": {
        "preheat": 'on stovetop heat oil',
        "preheatTemp": 350,
        "preheatUnit": "F",
        "prepareAhead": "Soak the chickpeas overnight and the fava beans for 2 nights",
        "yields":10,
        "yieldUnit":"each",
        "servings":10,
        "servingUnit":"each",
        "category":"vegetables",
        "subcategory":"beans",
        "tags": ["protein", "falafel"],
        "kosher": "pareve",
        "ingredients": [
            Ingredient("dried chickpeas", 312, qtyUnit='g'),
            Ingredient("dried fava beans", 312, qtyUnit='g'),
            Ingredient("parsley", 1, qtyUnit='bunch'),
            Ingredient("green onion", 3, qtyUnit='each'),
            Ingredient("cayenne powder", 2, qtyUnit='g'),
            Ingredient("cumin", 6, qtyUnit='g'),
            Ingredient("coriander", 2.5, qtyUnit='g'),
            Ingredient("garlic", 6, qtyUnit='clove'),
            Ingredient("baking powder", 3.75, qtyUnit='g'),
            Ingredient("salt", 15, qtyUnit='g'),
            Ingredient("vegetable oil", 960, qtyUnit='ml'),
        ],
        "times": {"active": "30 minutes", "cook": "10-20 minutes"},
        "steps": [
            "Soak the chickpeas overnight and the fava beans for 2 nights",
            "Rough dice the vegetables",
            "Add the chickpeas, vegetables, and spices to a food processor",
            "Pulse until a rough paste forms",
            "Form mixture into balls and flatten slightly",
            "Fry until golden brown in small batches, about 4 minutes per batch",
            "Remove from oil and drain on a paper towel",
            "Season with salt and serve immediately",
        ],

    },
    "sachet of spices" : {
        "yields":1,
        "yieldUnit":"each",
        "servings":1,
        "servingUnit":"each",
        "category":"mise en place",
        "subcategory":"herbs and spices",
        "tags": ["spice", "sachet"],
        "kosher": "pareve",
        "ingredients": [
            Ingredient("bay leaf", 1),
            Ingredient("thyme", 1, qtyUnit='sprig'),
            Ingredient("parsley", 3, qtyUnit='sprig'),
            Ingredient("black pepper", 10, "g"),
            Ingredient("garlic", 1, qtyUnit='clove'),
        ],
        "steps": [
            "Place all the ingredients in a cheesecloth and tie with twine",
            "Add to soups and sauces for flavor",
        ],
    },
    "oven roasted tomatoes" : {
        "preheat": 'preheat oven',
        "preheatTemp": 275,
        "preheatUnit": "F",
        "yields":10,
        "yieldUnit":"each",
        "servings":10,
        "servingUnit":"each",
        "category":"mise en place",
        "subcategory":"vegetables",
        "tags": ["vegetables", "tomato"],
        "kosher": "pareve",
        "ingredients": [
            Ingredient("tomato", 2.04, qtyUnit='kg'),
            Ingredient("olive oil", 90, qtyUnit='ml'),
            Ingredient("garlic", 14, qtyUnit='g', prep="minced"),
            Ingredient("shallot", 14, qtyUnit='g', prep="minced"),
            Ingredient("basil", 2, qtyUnit='g', prep="chopped"),
            Ingredient("oregano", 2, qtyUnit='g', prep="chopped"),
            Ingredient("thyme", 2, qtyUnit='g', prep="chopped"),
            Ingredient("salt", 15, qtyUnit='g'),
        ],
        "times": {"active":"10-15 minutes","cook": "60-90 minutes"},
        "steps": [
            "Cut the cores out of the tomatoes and cut into the desired shape. Halves, quartered, or sliced",
            "Combine oil, garlic, shallots, herbs, and salt in a bowl",
            "Drizzle this mixture over the tomatoes and turn carefully to coat them",
            "Arrange the tomatoes on racks on sheet pans", 
            "Roast in the oven at 275 F for 1 - 1.5 hours or until the tomatoes are dried and lightly browned",
            "They are ready to use now or can be stored in oil in the refrigerator for up to 2 weeks",
        ],
    },
    "roasted carrots" : {
        "preheat": 'preheat oven',
        "preheatTemp": 350,
        "preheatUnit": "F",
        "yields":4,
        "yieldUnit":"each",
        "servings":4,
        "servingUnit":"each",
        "category":"vegetables",
        "subcategory":"carrots",
        "tags": ["vegetables", "carrot"],
        "kosher": "pareve",
        "ingredients": [
            Ingredient("carrot", 450, qtyUnit='g'),
            Ingredient("grapeseed oil", 25, qtyUnit='g'),
            Ingredient("salt", 5, qtyUnit='g'),
        ],
        "times": {"active": "5-10 minutes", "cook": "30-45 minutes"},
        "steps": [
            "Peel the carrots and cut into 1 inch pieces. Oblique, rounds, or sticks. If the carrots are thin you can leave them whole",
            "Toss the carrots with oil and salt",
            "Roast in the oven at 350 F until the carrots are tender and browned",
        ],
    },
    "corn fritters" : {
        "preheat": 'stove top medium heat',
        "yields":10,
        "yieldUnit":"each",
        "servings":10,
        "servingUnit":"each",
        "category":"vegetables",
        "subcategory":"corn",
        "tags": ["bread", "fritter", "corn"],
        "kosher": "pareve",
        "ingredients": [
            Ingredient("corn", 1.13, qtyUnit='kg', prep="kernels"),
            Ingredient("lg egg", 2, prep="beaten"),
            Ingredient("cheddar cheese", 57, qtyUnit='g', prep="grated"),
            Ingredient("ap flour", 113, qtyUnit='g'),
            Ingredient("sugar", 57, qtyUnit='g'),
            Ingredient("salt", 5, qtyUnit='g'),
            Ingredient("black pepper", 1, qtyUnit='g'),
            Ingredient("vegetable oil", 1, qtyUnit='cup'),
        ],
        "times": {"active": "15-25 minutes", "cook": "10-15 minutes"},
        "steps": [
            "Combine the corn eggs and cheese in a bowl",
            "In a separate bowl combine the flour, sugar, salt, and pepper. Make a well in the center and add the corn mixture",
            "Stir until a smooth batter forms",
            "Heat the oil in a pan over medium heat. About 1 cm of oil",
            "Laddle 1 fl oz of the batter into the oil per fritter",
            "Cook until golden brown on both sides, 2-3 minutes per side",
        ],
    },
    "coconut rice" : {
        "yields":10,
        "yieldUnit":"each",
        "servings":10,
        "servingUnit":"each",
        "category":"grain",
        "subcategory":"rice",
        "tags": ["grain", "rice", "coconut"],
        "kosher": "pareve",
        "ingredients": [
            Ingredient("white rice", 392, qtyUnit='g', prep='rinsed'),
            Ingredient("grapeseed oil", 45, qtyUnit='ml'),
            Ingredient("coconut milk", 360, qtyUnit='ml'),
            Ingredient("water", 480, qtyUnit='ml'),
            Ingredient("salt", 5, qtyUnit='g'),
        ],
        "times": {"active": "5-10 minutes", "cook": "12-15 minutes", "rest": "5 minutes"},
        "steps": [
            "Rinse the rice until the water runs clear, drain well before using",
            "Heat oil in a heavy pot over medium heat",
            "Add the rice and saute until coated with oil and heated through",
            "Add water and coconut milk to the rice and season with salt and pepper",
            "Bring to a simmer then reduce the heat, cover and cook in a 350 F oven for 12-15 minutes",
            "Allow rice to rest for 5 minutes before fluffing with a fork"
        ],
    },
    "boiled rice" : {
        "preheat": 'bring water to boil',
        "yields":10,
        "yieldUnit":"each",
        "servings":10,
        "servingUnit":"each",
        "category":"grain",
        "subcategory":"rice",
        "tags": ["grain", "rice", "boiled rice"],
        "kosher": "pareve",
        "ingredients": [
            Ingredient("white rice", 1, qtyUnit='cup'),
            Ingredient("water", 2, qtyUnit='cup'),
            Ingredient("salt", 5, qtyUnit='g'),
        ],
        "times": {"active": "2-5 minutes", "cook": "15-20 minutes", "rest": "5 minutes"},
        "steps": [
            "Bring the water to a boil",
            "Rinse the rice until the water runs clear, drain well before using",
            "Add salt to the boiling water"
            "Add the rice in a thin stream to the water, breaking up with a fork as you go",
            "When the water returns to a boil reduce the heat to a simmer",
            "Cook until the rice is tender, about 15-20 minutes",
            "Drain immediately into a colander and place the colander over the pot to steam the rice dry. ~ 5 minutes",
            "Fluff the rice with a fork",
        ],
    },
    "pasta": {
        "yields":680,
        "yieldUnit":"g",
        "servings":10,
        "servingUnit":"each",
        "category":"pasta",
        "subcategory":"fresh",
        "tags": ["grain", "pasta"],
        "kosher": "pareve",
        "ingredients": [
            Ingredient("ap flour", 454, qtyUnit='g'),
            Ingredient("lg egg", 4, qtyUnit='each'),
            Ingredient("water", 30, qtyUnit='ml'),
            Ingredient("salt", 5, qtyUnit='g'),
            Ingredient("olive oil", 15, qtyUnit='ml'),
        ],
        "times": {"active": "25-40 minutes", "rest": "1 hour"},
        "steps": [
            "Combine the flour and salt in a large bowl and create a well in the center",
            "Place the eggs, water and oil in the well and mix with a fork until a shaggy dough forms",
            "Adjust as needed with more water or flour",
            "Knead the dough until smooth and elastic, about 4-5 minutes",
            "Gather into a ball and wrap in plastic wrap, let rest for at least 1 hour",
            "Roll out the dough to the desired thickness and cut into the desired shape",
        ],
    },
    "ginger soy dipping sauce" : {
        "yields":480,
        "yieldUnit":"ml",
        "servings":480/60,
        "servingUnit":"each",
        "category":"sauces",
        "subcategory":"dipping",
        "tags": ["sauces", "dipping"],
        "kosher": "pareve",
        "ingredients": [
            Ingredient("ginger", 71, qtyUnit='g', prep="minced"),
            Ingredient("light soy sauce", 120, qtyUnit='ml'),
            Ingredient("rice vinegar", 240, qtyUnit='ml'),
            Ingredient("water", 240, qtyUnit='ml'),
            Ingredient("sesame oil", 30, qtyUnit='ml'),
            Ingredient("sugar", 56, qtyUnit='g'),
        ],
        "times": {"active": "5-10 minutes"},    
        "steps": [
            "Whisk together all the ingredients in a bowl until sugar is dissolved",
        ],
    },
    "apple cider vinaigrette" : {
        "yields":480,
        "yieldUnit":"ml",
        "servings":480/60,
        "servingUnit":"each",
        "category":"sauces",
        "subcategory":"salad dressing",
        "tags": ["sauces", "vinaigrette"],
        "kosher": "pareve",
        "times": {"active": "5-10 minutes"},
        "ingredients": [
            Ingredient("apple cider", 240, qtyUnit='ml'),
            Ingredient("apple cider vinegar", 90, qtyUnit='ml'),
            Ingredient("granny smith apple", 0.5, qtyUnit='each', prep="grated"),
            Ingredient("salt", 5, qtyUnit='g'),
            Ingredient("black pepper", 1, qtyUnit='g'),
            Ingredient("vegetable oil", 360, qtyUnit='ml'),
            Ingredient("tarragon", 3, qtyUnit='ml', prep="minced"),
            Ingredient("maple syrup", 2, qtyUnit='tsp'),
        ],
        "steps": [
            "Simmer the cider to that its reduced 2/3rds and cool",
            "Combine the cider reduction, vinegar, apple, salt, pepper",
            "Gradually whisk in the oil",
            "Stir in the tarragon and maple syrup",
            "Season with salt and pepper",
        ],
    },
    "balsamic vinaigrette" : {
        "yields":480,
        "yieldUnit":"ml",
        "servings":480/30,
        "servingUnit":"each",
        "category":"sauces",
        "subcategory":"salad dressing",
        "tags": ["sauces", "vinaigrette"],
        "kosher": "pareve",
        "ingredients": [
            Ingredient("red wine vinegar", 60, qtyUnit='ml'),
            Ingredient("balsamic vinegar", 60, qtyUnit='ml'),
            Ingredient("dijon mustard", 5, qtyUnit='g'),
            Ingredient("vegetable oil", 360, qtyUnit='ml'),
            Ingredient("salt", 5, qtyUnit='g'),
            Ingredient("black pepper", 1, qtyUnit='g'),
        ],
        "steps": [
            "Whisk together the vinegar, mustard, salt, and pepper",
            "Gradually whisk in the oil",
            "Season with salt and pepper",
            "Add optional herbs"
        ],
    },
    "simple syrup" : {
        "yields":960,
        "yieldUnit":"ml",
        "servings":960/CUP,
        "servingUnit":"cup",
        "category":"mise en place",
        "subcategory":"liquids",
        "tags": ["sauces", "simple syrup"],
        "kosher": "pareve",
        "ingredients": [
            Ingredient("sugar", 454, qtyUnit='g'),
            Ingredient("water", 480, qtyUnit='ml'),
        ],
        "times": {"active": "5-10 minutes"},
        "steps": [
            "Combine the sugar and water in a pot",
            "Bring to a boil and simmer until the sugar is dissolved",
            "Cool before using",
        ],
    },
    "naan":{
        "preheat": "oven",
        "preheatTemp": 425,
        "yields":8,
        "yieldUnit":"each",
        "servings":8,
        "servingUnit":"each",
        "category":"bread",
        "subcategory":"flatbread",
        "tags": ["bread", "naan"],
        "kosher": "pareve",
        "ingredients": [
            Ingredient("ap flour", 397, qtyUnit='g'),
            Ingredient("instant dry yeast", 9, qtyUnit='g'),
            Ingredient("water", 180, qtyUnit='ml'),
            Ingredient("vegetable oil", 60, qtyUnit='ml'),
            Ingredient("plain yogurt", 57, qtyUnit='g'),
            Ingredient("lg egg", 1),
            Ingredient("sugar", 28, qtyUnit='g'),
            Ingredient("salt", 7.5, qtyUnit='g'),
        ],
        "times": {"active": "15 minutes", "proof": "60-90 minutes", "cook": "10-12 minutes"},
        "steps": [
            "Combine the flour and yeast. Add the water, oil, yogurt, egg, sugar, and salt and mix on low speed for 4 minutes",
            "Dough should be very elastic but still wet",
            "Bulk ferment for 1 hour or until doubled in size",
            "Portion into 8 pieces and pre-shape into rounds",
            "Cover and rest for 15 minutes until dough relaxes",
            "Stretch the dough into rounds around 7 inches in diameter, center should be aroud 1/4 inch thick, and a little thicker at the edges",
            "Pull one side of the dough and stretch it out to form a teardrop shape",
            "Place on a baking sheet lined with parchment and brush with oil",
            "Bake for 10-12 minutes or until golden brown",
        ],
    },
    "better than bouillon" : {
        "preheat": "boil water",
        "yields":1.5,
        "yieldUnit":"l",
        "servings":1500/CUP,
        "servingUnit":"cup",
        "category":"mise en place",
        "subcategory":"stock",
        "tags": ["stock", "better than bouillon"],
        "kosher": "pareve",
        "ingredients": [
            Ingredient("better than bouillon", 1, qtyUnit='tbsp'),
            Ingredient("water", 1500, qtyUnit='ml'),
        ],
        "times": {"active": "5 minutes"},
        "steps": [
            "Bring water to boil",
            "Add better than bouillon and stir until dissolved",
        ],
    },

}