from modules.ingredients import Ingredient
from modules.recipe import Recipe
from constants import *

# Create a bread recipe
compoundRecipes = {
    "toast with butter" : {
        "preheat":"",
        "preheatTemp": None,
        "yields":1,
        "yieldUnit":"slice",
        "servings":1,
        "servingUnit":"slice",
        "category":"bread",
        "subcategory":"toast",
        "notes":"",
        "tags": ["bread", "toast", "butter"],
        "kosher": "pareve",
        "ingredients": [
            Recipe("peasant bread", servingQty=1, servingUnit='slice'),
            Ingredient("salted butter", 2, qtyUnit='tsp'),
        ],
        "steps": [
            "Toast the bread",
            "Spread the butter on the toast"
        ],
    },
    "toast with peanut butter" : {
        "preheat":"",
        "preheatTemp": None,
        "yields":1,
        "yieldUnit":"slice",
        "servings":1,
        "servingUnit":"slice",
        "category":"bread",
        "subcategory":"toast",
        "notes":"",
        "tags": ["bread", "toast", "peanut butter"],
        "kosher": "pareve",
        "ingredients": [
            Recipe("peasant bread", servingQty=1, servingUnit='slice'),
            Ingredient("peanut butter", 1, qtyUnit='tbsp'),
        ],
        "steps": [
            "Toast the bread",
            "Spread the peanut butter on the toast"
        ],
    },
    "french toast" : {
        "preheat": 'stove top medium heat',
        "preheatTemp": None,
        "yields":2,
        "yieldUnit":"slice",
        "servings":2,
        "servingUnit":"slice",
        "category":"bread",
        "subcategory":"french toast",
        "notes":"",
        "tags": ["bread", "french toast"],
        "kosher": "pareve",
        "ingredients": [
            Recipe("peasant bread", servingQty=2, servingUnit='slice'),
            Ingredient("lg egg", 2),
            Ingredient("water", 1, qtyUnit='tbsp'),
            Ingredient("grapeseed oil", 1, qtyUnit='tsp'),
            Ingredient("salt", 1, qtyUnit='tsp'), 
        ],
        "steps": [
            "Heat the oil in a pan over medium heat",
            "Whisk the egg, water, and salt in a bowl",
            "Soak the bread in the egg mixture",
            "Fry the bread until golden brown on both sides",
        ],
    },
    "challah french toast" : {
        "preheat": 'stove top medium heat',
        "preheatTemp": None,
        "yields":2,
        "yieldUnit":"slice",
        "servings":2,
        "servingUnit":"slice",
        "category":"bread",
        "subcategory":"french toast",
        "notes":"",
        "tags": ["bread", "french toast", "challah"],
        "kosher": "pareve",
        "ingredients": [
            Recipe("challah", servingQty=2, servingUnit='slice'),
            Ingredient("lg egg", 2),
            Ingredient("water", 1, qtyUnit='tbsp'),
            Ingredient("grapeseed oil", 1, qtyUnit='tsp'),
            Ingredient("salt", 1, qtyUnit='tsp'), 
        ],
        "steps": [
            "Heat the oil in a pan over medium heat",
            "Whisk the egg, water, and salt in a bowl",
            "Soak the bread in the egg mixture",
            "Fry the bread until golden brown on both sides",
        ],
    },
    "fine vegetable stock" : {
        "preheat": 'stove top medium heat',
        "preheatTemp": None,
        "yields":3.84,
        "yieldUnit":"l",
        "servings":3840/CUP,
        "servingUnit":"cup",
        "category":"stock",
        "subcategory":"vegetable",
        "notes":"",
        "tags": ["stock", "vegetable"],
        "kosher": "pareve",
        "ingredients": [
            Ingredient("grapeseed oil", 60, qtyUnit='ml'),
            Recipe("mirepoix", servingQty=1.36, servingUnit='kg'), 
            Ingredient("garlic", 3, qtyUnit='each'),
            Ingredient("leek", 400, qtyUnit='g'),
            Ingredient("bell pepper", 400, qtyUnit='g'),
            Ingredient("jalapeno", 3),
            Ingredient("salt", 2, qtyUnit='tsp'),
            Ingredient("water", 4.8, qtyUnit='l'),
        ],
        "steps": [
            "Rough chop the vegetables",
            "Add the vegetables to a pot with the oil and saute until soft",
            "Add the water and salt",
            "Bring to a boil and simmer for 1 hour",
            "Strain the stock and discard the vegetables",
        ],
    },
    "lentil soup": {
        "preheat": 'stove top medium heat',
        "preheatTemp": None,
        "yields":1.92,
        "yieldUnit":"l",
        "servings":1920/CUP,
        "servingUnit":"cup",
        "category":"soup",
        "subcategory":"lentil",
        "notes":"",
        "tags": ["soup", "lentil"],
        "kosher": "pareve",
        "ingredients": [
            Ingredient("grapeseed oil", 30, qtyUnit='ml'),
            Ingredient("onion", 1, qtyUnit='each'),
            Recipe("mirepoix", servingQty=227, servingUnit='g'),
            Ingredient("garlic", 4, qtyUnit='each'),
            Ingredient("dried green lentils", 400, qtyUnit='g'),
            Recipe("scrap vegetable stock", yieldQty=2.85, yieldUnit='l'),
            Recipe("lemon juice", yieldQty=30, yieldUnit='ml'),
            Ingredient("salt", 2, qtyUnit='tsp'),
        ],
        "steps": [
            "Rough chop the vegetables",
            "Add the vegetables to a pot with the oil and saute until soft",
            "Add the water, lentils, and salt",
            "Bring to a boil and simmer for 1 hour",
            "Blend the soup",
        ],
    },
    "mango chutney": {
        "preheat": None,
        "preheatTemp": None,
        "yields": 430,
        "yieldUnit":"ml",
        "servings":430/TBSP,
        "servingUnit":"tbsp",
        "category":"sauce",
        "subcategory":"chutney",
        "tags": ["sauce", "chutney", "mango"],
        "kosher": "pareve",
        "ingredients": [
            Ingredient("mango", 2, qtyUnit='each'),
            Recipe("lime juice", yieldQty=30, yieldUnit='ml'),
            Ingredient("cilantro", 2, qtyUnit='g'),
            Ingredient("onion", 1, qtyUnit='each'),
            Ingredient("ginger", 30, qtyUnit='g'),
            Ingredient("jalapeno", 4, qtyUnit='each'),
            Ingredient("salt", 1, qtyUnit='tsp'),
        ],
        "steps": [
            "Dice the mango, onion, ginger, and jalapeno",
            "Add all the ingredients and let rest in a refrigerator for up to 2 hour",
            "Adjust seasoning as necessary",
        ],
    },
    "potato pancakes": {
        "preheat": 'stove top medium heat',
        "preheatTemp": None,
        "yields": 10,
        "yieldUnit":"each",
        "servings":10,
        "servingUnit":"each",
        "category":"bread",
        "subcategory":"pancake",
        "tags": ["bread", "pancake", "potato"],
        "kosher": "pareve",
        "ingredients": [
            Ingredient("russet potato", 1.36, qtyUnit='kg'),
            Ingredient("onion", 454, qtyUnit='g'),
            Recipe("lemon juice", servingQty=30, servingUnit='ml'),
            Ingredient("lg egg", 2),
            Ingredient("ap flour", 28, qtyUnit='g'),
            Ingredient("matzo meal", 28, qtyUnit='g'),
            Ingredient("grapeseed oil", 120, qtyUnit='ml'),
        ],
        "steps": [
            "Grate the potato and onion and toss in lemon juice to prevent browning",
            "Squeeze out the excess liquid",
            "Transfer to a bowl and add the egg, flour, and matzo meal",
            "Fry the mixture in a pan until golden brown on both sides, season with salt and pepper to taste",
        ],
    },
    "boiled white beans" : {
        "preheat": 'stove top medium heat',
        "preheatTemp": None,
        "yields":1,
        "yieldUnit":"each",
        "servings":10,
        "servingUnit":"each",
        "category":"protein",
        "subcategory":"bean",
        "notes":"",
        "tags": ["protein", "bean"],
        "kosher": "pareve",
        "ingredients": [
            Ingredient("dried navy beans", 454, qtyUnit='g'),
            Ingredient("vegetable oil", 30, qtyUnit='ml'),
            Ingredient("water", 1, qtyUnit='l'),
            Ingredient("onion", 113, qtyUnit='g'),
            Recipe("scrap vegetable stock", yieldQty=1.92, yieldUnit='l'),
            Recipe("sachet of spices", 1),
        ],
        "steps": [
            "Soak the beans overnight",
            "Heat the oil in a pot over medium heat",
            "Add the onion and sweat until translucent",
            "Add the beans, stock, and sachet of spices",
            "Bring to a boil and simmer for around 1 hour",
            "Season with salt and pepper and simmer until beans are tender",
            "Remove the sachet of spices",
            "Beans can be strained and used immediately or stored in the liquid",

        ],
    },
    "mixed bean salad" : {
        "preheat": None,
        "preheatTemp": None,
        "yields": 10,
        "yieldUnit":"each",
        "servings":10,
        "servingUnit":"each",
        "category":"salad",
        "subcategory":"bean",
        "tags": ["salad", "bean"],
        "kosher": "pareve",
        "ingredients": [
            Ingredient("dried black beans", 284, qtyUnit='g', prep="cooked"),
            Ingredient("dried pinto beans", 284, qtyUnit='g', prep="cooked"),
            Ingredient("dried chickpeas", 284, qtyUnit='g', prep="cooked"),
            Ingredient("dried red lentils", 142, qtyUnit='g', prep="cooked"),
            Ingredient("red onion", 170, qtyUnit='g', prep="diced"),
            Ingredient("parsley", 1, qtyUnit='each', prep="minced"),
            Ingredient("celery", 30, qtyUnit='g', prep="minced"),
            Recipe("balsamic vinaigrette", yieldQty=30, yieldUnit='ml'),
            Ingredient("salt", 1, qtyUnit='tsp'),
        ],
        "steps": [
            "Dice the onion, parsley, and celery",
            "Mix all the ingredients and let marinade in a refrigerator for at least 24 hours",
            "Adjust seasoning as necessary",
        ],
    },
    "guacamole" : {
        "preheat": None,
        "preheatTemp": None,
        "yields":480,
        "yieldUnit":"ml",
        "servings":480/60, # 2 oz servings
        "servingUnit":"each",
        "category":"sauce",
        "subcategory":"guacamole",
        "tags": ["sauce", "guacamole"],
        "kosher": "pareve",
        "ingredients": [
            Ingredient("avocado", 3),
            Ingredient("red onion", 64, qtyUnit='g', prep="small dice"),
            Ingredient("jalapeno", 7, qtyUnit='g', prep="seeded and minced"),
            Ingredient("cilantro", 3, qtyUnit='g', prep="chopped"),
            Ingredient("garlic", 1, qtyUnit='clove'),
            Recipe("lime juice", yieldQty=45, yieldUnit='ml'),
            Ingredient("salt", 5, qtyUnit='g'),
            Ingredient("black pepper", 1, qtyUnit='g'),
        ],
        "steps": [
            "Soak the onions in cold water for 20 minutes, drain and rinse, dry well",
            "Peel the avcado and cut roughly into a medium dice",
            "Add the jalapeno, garlic, lime juice, salt, pepper, and cilantro",
            "Mash the ingredients together until desired consistency",
            "Season with salt and pepper",
        ],
    },
    "hummus": {
        "preheat": None,
        "preheatTemp": None,
        "yields": 960,
        "yieldUnit":"ml",
        "servings":960/60, # 2 oz servings
        "servingUnit":"each",
        "category":"sauce",
        "subcategory":"hummus",
        "tags": ["sauce", "hummus"],
        "kosher": "pareve",
        "ingredients": [
            Ingredient("dried chickpeas", 340, qtyUnit='g', prep="soaked overnight"),
            Recipe("lemon juice", yieldQty=150, yieldUnit='ml'),
            Ingredient("garlic", 3, qtyUnit='clove'),
            Ingredient("olive oil", 90, qtyUnit='ml'),
            Ingredient("tahini", 128, qtyUnit='g'),
            Ingredient("salt", 5, qtyUnit='g'),
        ],
        "steps": [
            "Boil the chickpeas in water until tender, 1-2 hours. Drain the chickpeas and reserve the cooking liquid",
            "In a food processor blend the chickpeas with 120 ml of the reserved cooking liquid until smooth paste",
            "Add the lemon juice, garlic, oil, tahini, and salt and process until well combined",
            "Adjust seasoning as necessary",
        ],
    },
    "baba ghanoush": {
        "preheat": 'oven',
        "preheatTemp": 450,
        "yields": 480,
        "yieldUnit":"ml",
        "servings":480/60, # 2 oz servings
        "servingUnit":"each",
        "category":"sauce",
        "subcategory":"baba ganoush",
        "tags": ["sauce", "baba ganoush"],
        "kosher": "pareve",
        "ingredients": [
            Ingredient("eggplant", 900, qtyUnit='g'),
            Ingredient("tahini", 85, qtyUnit='g'),
            Ingredient("garlic", 14, qtyUnit='g', prep="rough chop"),
            Recipe("lemon juice", yieldQty=90, yieldUnit='ml'),
            Ingredient("parsley", 43, qtyUnit='g', prep="chopped"),
            Ingredient("salt", 5, qtyUnit='g'),
        ],
        "steps": [
            "Slice the eggplant in half and roast cut side down in the oven at 450 F until skin is charred, around 1 to 1.5 hours",
            "Peel the eggplant and blend with the garlic, oil, tahini, lemon juice, and salt",
            "Blend until homogenous. If too thick, add water to thin",
            "When mixutre is smooth, add the parsley and adjust seasoning as necessary",
        ],
    },
    "harissa": {
        "preheat": None,
        "preheatTemp": None,
        "yields": 960,
        "yieldUnit":"ml",
        "servings":960/TBSP, # 2 oz servings
        "servingUnit":"tbsp",
        "category":"sauce",
        "subcategory":"harissa",
        "tags": ["sauce", "harissa"],
        "kosher": "pareve",
        "ingredients": [
            Ingredient("dried habanero", 16, qtyUnit='each'),
            Ingredient("cayenne", 1.8, qtyUnit='kg', prep="seeded"),
            Ingredient("sun-dried tomato", 3, qtyUnit='clove'),
            Ingredient("garlic", 43, qtyUnit='g'),
            Ingredient("ground tumeric", 43, qtyUnit='g'),
            Ingredient("cumin", 4, qtyUnit='g', prep="ground"),
            Ingredient("coriander", 4, qtyUnit='g', prep="ground"),
            Ingredient("caraway", 4, qtyUnit='g'),
            Recipe("lemon juice", yieldQty=10, yieldUnit='ml'),
            Ingredient("olive oil", 60, qtyUnit='ml'),
            Ingredient("salt", 5, qtyUnit='g'),
        ],
        "steps": [
            "Toss the habaneros in a hot pan until the skin blackens and a little smoke rises, about 15 seconds per side",
            "Hydrate the chilis in warm water for 30 minutes",
            "When they are hydrated, remove the seeds and stems",
            "Blend the chilis with the garlic, cumin, coriander, caraway, and salt",
            "Adjust the consistency with the lemon juice and olive oil",
            "Adjust seasoning as necessary",
        ],
    },
    "Z'hug":{
        "preheat": None,
        "preheatTemp": None,
        "yields": 480,
        "yieldUnit":"ml",
        "servings":480/TBSP, 
        "servingUnit":"tbsp",
        "category":"sauce",
        "subcategory":"z'hug",
        "tags": ["sauce", "z'hug"],
        "kosher": "pareve",
        "ingredients": [
            Ingredient("jalapeno", 725, qtyUnit='g'),
            Ingredient("garlic", 25, qtyUnit='g'),
            Ingredient("cilantro", 100, qtyUnit='g'),
            Ingredient("parsley", 50, qtyUnit='g'),
            Ingredient("mint", 50, qtyUnit='g'),
            Ingredient("cumin", 4, qtyUnit='g', prep="toasted"),
            Ingredient("cardamom", 5, qtyUnit='g', prep="peeled, seeds toasted"),
            Ingredient("olive oil", 240, qtyUnit='ml'),
            Recipe("lemon juice", yieldQty=90, yieldUnit='ml'),
            Ingredient("salt", 5, qtyUnit='g'),
            Ingredient("black pepper", 4, qtyUnit='g', prep="ground"),
        ],
        "steps": [
            "Roast the japaleno in a hot pan until the skin blackens and a little smoke rises, about 15 seconds per side",
            "Blend the jalapeno, garlic, cilantro, parsley, mint, cumin, cardamom, salt, and pepper",
            "Slowly add the olive oil while continuing to blend",
            "Season with lemon juice, salt and pepper",
        ],
    },
        "risotto": {
        "preheat": None,
        "preheatTemp": None,
        "yields":10,
        "yieldUnit":"each",
        "servings":10,
        "servingUnit":"each",
        "category":"grain",
        "subcategory":"rice",
        "tags": ["grain", "rice", "risotto"],
        "kosher": "pareve",
        "ingredients": [
            Ingredient("onion", 57, qtyUnit='g', prep="minced"),
            Ingredient("butter", 57, qtyUnit='g'),
            Ingredient("arborio rice", 397, qtyUnit='g'),
            Recipe("scrap vegetable stock", yieldQty=1.44, yieldUnit='l'),
        ],
        "steps": [
            "In a medium pot, add the oil and sweat the onions until translucent, 6-8 minutes",
            "Add the rice and toast until the rice is aromatic, about 1 minute",
            "Add the stock 1/3 at a time, stirring frequently until the stock is absorbed before adding more. Alternative to stirring, shaking the pot causes the rice to rub the starch off the grains and create a creamy texture",
            "Cook until the rice is tender and creamy, about 20 minutes",
            "Add the butter and cheese and stir until melted",
        ],
    },
        "rice and beans" : {
        "preheat": None,
        "preheatTemp": None,
        "yields":10,
        "yieldUnit":"each",
        "servings":10,
        "servingUnit":"each",
        "category":"grain",
        "subcategory":"rice",
        "tags": ["grain", "rice", "beans"],
        "kosher": "pareve",
        "ingredients": [
            Ingredient("dried kidney beans", 454, qtyUnit='g', prep="soaked"),
            Ingredient("grapeseed oil", 30, qtyUnit='ml'),
            Ingredient("nutritional yeast", 1, qtyUnit='tbsp'),
            Ingredient("garlic", 2, qtyUnit='clove', prep="minced"),
            Recipe("scrap vegetable stock", yieldQty=1.44, yieldUnit='l'),
            Ingredient("white rice", 142, qtyUnit='g'),
            Ingredient("coconut milk", 240, qtyUnit='ml'),
            Ingredient("green onion", 45, qtyUnit='g'),
        ],
        "steps": [
            "In a medium pot, add the garlic and sweat until aroatmatic",
            "Add the stock, beans and oil",
            "Bring to a boil and then bring down to a simmer for 1 hour or until beans are tender",
            "Rinse the rice until the water runs clear, drain rice well before using",
            "Add the rice and coconut milk to the pot",
            "Cover and simmer until rice is tender, about 20 minutes, or until all the liquid is absorbed"
        ],
    },
            "mushroom risotto": {
        "preheat": None,
        "preheatTemp": None,
        "yields":10,
        "yieldUnit":"each",
        "servings":10,
        "servingUnit":"each",
        "category":"grain",
        "subcategory":"rice",
        "tags": ["grain", "rice", "risotto"],
        "kosher": "pareve",
        "ingredients": [
            Ingredient("onion", 57, qtyUnit='g', prep="minced"),
            Ingredient("butter", 57, qtyUnit='g'),
            Ingredient("arborio rice", 397, qtyUnit='g'),
            Ingredient("dried wild mushrooms", 85, qtyUnit='g'),
            Recipe("scrap vegetable stock", yieldQty=1.44, yieldUnit='l'),
        ],
        "steps": [
            "Soak the wildmushrooms in water for 30-60 minutes",
            "Drain the mushrooms and reserve the liquid",
            "Strain the liquid through a coffee filter to remove any grit and substitute it for the stock",
            "In a medium pot, add the oil and sweat the onions and mushrooms until the onions are translucent, 6-8 minutes",
            "Add the rice and toast until the rice is aromatic, about 1 minute",
            "Add the stock 1/3 at a time, stirring frequently until the stock is absorbed before adding more. Alternative to stirring, shaking the pot causes the rice to rub the starch off the grains and create a creamy texture",
            "Cook until the rice is tender and creamy, about 20 minutes",
            "Add the butter and cheese and stir until melted",
        ],
    },
        "mayonnaise" : {
        "preheat": None,
        "preheatTemp": None,
        "yields":960,
        "yieldUnit":"ml",
        "servings":960/15,
        "servingUnit":"tbsp",
        "category":"sauce",
        "subcategory":"mayonnaise",
        "tags": ["sauce", "mayonnaise"],
        "kosher": "pareve",
        "ingredients": [
            Ingredient("lg egg yolk", 75),
            Ingredient("water", 30, qtyUnit='ml'),
            Ingredient("white wine vinegar", 30, qtyUnit='ml'),
            Ingredient("dijon mustard", 10, qtyUnit='g'),
            Ingredient("sugar", 5, qtyUnit='g'),
            Ingredient("vegetable oil", 720, qtyUnit='ml'),
            Recipe("lemon juice", yieldQty=30, yieldUnit='ml'),
            Ingredient("salt", 5, qtyUnit='g'),
        ],
        "steps": [
            "Whisk together the egg yolk, water, vinegar, mustard, and sugar with a balloon whisk until slightly foamy",
            "Gradually whisk in the oil constantly whisking until the mixture is smooth and thick",
            "Season with lemon juice, salt, and pepper",
        ],
    },
}