from modules.ingredients import Ingredient
from modules.recipe import Recipe
from constants import *

# Create a bread recipe
compoundRecipes = {
    "toast with butter" : {
        "preheat":"",
        "preheatTemp": None,
        "yields":1,
        "yieldUnit":"slice",
        "servings":1,
        "servingUnit":"slice",
        "category":"bread",
        "subcategory":"toast",
        "notes":"",
        "tags": ["bread", "toast", "butter"],
        "kosher": "pareve",
        "ingredients": [
            Recipe("peasant bread", servingQty=1, servingUnit='slice'),
            Ingredient("salted butter", 2, qtyUnit='tsp'),
        ],
        "steps": [
            "Toast the bread",
            "Spread the butter on the toast"
        ],
    },
    "toast with peanut butter" : {
        "preheat":"",
        "preheatTemp": None,
        "yields":1,
        "yieldUnit":"slice",
        "servings":1,
        "servingUnit":"slice",
        "category":"bread",
        "subcategory":"toast",
        "notes":"",
        "tags": ["bread", "toast", "peanut butter"],
        "kosher": "pareve",
        "ingredients": [
            Recipe("peasant bread", servingQty=1, servingUnit='slice'),
            Ingredient("peanut butter", 1, qtyUnit='tbsp'),
        ],
        "steps": [
            "Toast the bread",
            "Spread the peanut butter on the toast"
        ],
    },
    "french toast" : {
        "preheat": 'stove top medium heat',
        "preheatTemp": None,
        "yields":2,
        "yieldUnit":"slice",
        "servings":2,
        "servingUnit":"slice",
        "category":"bread",
        "subcategory":"french toast",
        "notes":"",
        "tags": ["bread", "french toast"],
        "kosher": "pareve",
        "ingredients": [
            Recipe("peasant bread", servingQty=2, servingUnit='slice'),
            Ingredient("lg egg", 2),
            Ingredient("water", 1, qtyUnit='tbsp'),
            Ingredient("grapeseed oil", 1, qtyUnit='tsp'),
            Ingredient("salt", 1, qtyUnit='tsp'), 
        ],
        "steps": [
            "Heat the oil in a pan over medium heat",
            "Whisk the egg, water, and salt in a bowl",
            "Soak the bread in the egg mixture",
            "Fry the bread until golden brown on both sides",
        ],
    },
    "challah french toast" : {
        "preheat": 'stove top medium heat',
        "preheatTemp": None,
        "yields":2,
        "yieldUnit":"slice",
        "servings":2,
        "servingUnit":"slice",
        "category":"bread",
        "subcategory":"french toast",
        "notes":"",
        "tags": ["bread", "french toast", "challah"],
        "kosher": "pareve",
        "ingredients": [
            Recipe("challah", servingQty=2, servingUnit='slice'),
            Ingredient("lg egg", 2),
            Ingredient("water", 1, qtyUnit='tbsp'),
            Ingredient("grapeseed oil", 1, qtyUnit='tsp'),
            Ingredient("salt", 1, qtyUnit='tsp'), 
        ],
        "steps": [
            "Heat the oil in a pan over medium heat",
            "Whisk the egg, water, and salt in a bowl",
            "Soak the bread in the egg mixture",
            "Fry the bread until golden brown on both sides",
        ],
    },
    "fine vegetable stock" : {
        "preheat": 'stove top medium heat',
        "preheatTemp": None,
        "yields":3.84,
        "yieldUnit":"l",
        "servings":3840/CUP,
        "servingUnit":"cup",
        "category":"stock",
        "subcategory":"vegetable",
        "notes":"",
        "tags": ["stock", "vegetable"],
        "kosher": "pareve",
        "ingredients": [
            Ingredient("grapeseed oil", 60, qtyUnit='ml'),
            Recipe("mirepoix", servingQty=1.36, servingUnit='kg'), 
            Ingredient("garlic", 3, qtyUnit='each'),
            Ingredient("leek", 400, qtyUnit='g'),
            Ingredient("bell pepper", 400, qtyUnit='g'),
            Ingredient("jalapeno", 3),
            Ingredient("salt", 2, qtyUnit='tsp'),
            Ingredient("water", 4.8, qtyUnit='l'),
        ],
        "steps": [
            "Rough chop the vegetables",
            "Add the vegetables to a pot with the oil and saute until soft",
            "Add the water and salt",
            "Bring to a boil and simmer for 1 hour",
            "Strain the stock and discard the vegetables",
        ],
    },
    "lentil soup": {
        "preheat": 'stove top medium heat',
        "preheatTemp": None,
        "yields":1.92,
        "yieldUnit":"l",
        "servings":1920/CUP,
        "servingUnit":"cup",
        "category":"soup",
        "subcategory":"lentil",
        "notes":"",
        "tags": ["soup", "lentil"],
        "kosher": "pareve",
        "ingredients": [
            Ingredient("grapeseed oil", 30, qtyUnit='ml'),
            Ingredient("onion", 1, qtyUnit='each'),
            Recipe("mirepoix", servingQty=227, servingUnit='g'),
            Ingredient("garlic", 4, qtyUnit='each'),
            Ingredient("dry green lentils", 400, qtyUnit='g'),
            Recipe("scrap vegetable stock", yieldQty=2.85, yieldUnit='l'),
            Recipe("lemon juice", yieldQty=30, yieldUnit='ml'),
            Ingredient("salt", 2, qtyUnit='tsp'),
        ],
        "steps": [
            "Rough chop the vegetables",
            "Add the vegetables to a pot with the oil and saute until soft",
            "Add the water, lentils, and salt",
            "Bring to a boil and simmer for 1 hour",
            "Blend the soup",
        ],
    },
    "mango chutney": {
        "preheat": None,
        "preheatTemp": None,
        "yields": 430,
        "yieldUnit":"ml",
        "servings":430/TBSP,
        "servingUnit":"tbsp",
        "category":"sauce",
        "subcategory":"chutney",
        "tags": ["sauce", "chutney", "mango"],
        "kosher": "pareve",
        "ingredients": [
            Ingredient("mango", 2, qtyUnit='each'),
            Recipe("lime juice", yieldQty=30, yieldUnit='ml'),
            Ingredient("cilantro", 2, qtyUnit='g'),
            Ingredient("onion", 1, qtyUnit='each'),
            Ingredient("ginger", 30, qtyUnit='g'),
            Ingredient("jalapeno", 4, qtyUnit='each'),
            Ingredient("salt", 1, qtyUnit='tsp'),
        ],
        "steps": [
            "Dice the mango, onion, ginger, and jalapeno",
            "Add all the ingredients and let rest in a refrigerator for up to 2 hour",
            "Adjust seasoning as necessary",
        ],
    },
    "potato pancakes": {
        "preheat": 'stove top medium heat',
        "preheatTemp": None,
        "yields": 10,
        "yieldUnit":"each",
        "servings":10,
        "servingUnit":"each",
        "category":"bread",
        "subcategory":"pancake",
        "tags": ["bread", "pancake", "potato"],
        "kosher": "pareve",
        "ingredients": [
            Ingredient("russet potato", 1.36, qtyUnit='kg'),
            Ingredient("onion", 454, qtyUnit='g'),
            Recipe("lemon juice", servingQty=30, servingUnit='ml'),
            Ingredient("lg egg", 2),
            Ingredient("ap flour", 28, qtyUnit='g'),
            Ingredient("matzo meal", 28, qtyUnit='g'),
            Ingredient("grapeseed oil", 120, qtyUnit='ml'),
        ],
        "steps": [
            "Grate the potato and onion and toss in lemon juice to prevent browning",
            "Squeeze out the excess liquid",
            "Transfer to a bowl and add the egg, flour, and matzo meal",
            "Fry the mixture in a pan until golden brown on both sides, season with salt and pepper to taste",
        ],
    },
    "boiled white beans" : {
        "preheat": 'stove top medium heat',
        "preheatTemp": None,
        "yields":1,
        "yieldUnit":"each",
        "servings":10,
        "servingUnit":"each",
        "category":"protein",
        "subcategory":"bean",
        "notes":"",
        "tags": ["protein", "bean"],
        "kosher": "pareve",
        "ingredients": [
            Ingredient("dried navy beans", 454, qtyUnit='g'),
            Ingredient("vegetable oil", 30, qtyUnit='ml'),
            Ingredient("water", 1, qtyUnit='l'),
            Ingredient("onion", 113, qtyUnit='g'),
            Recipe("scrap vegetable stock", yieldQty=1.92, yieldUnit='l'),
            Recipe("sachet of spices", 1),
        ],
        "steps": [
            "Soak the beans overnight",
            "Heat the oil in a pot over medium heat",
            "Add the onion and sweat until translucent",
            "Add the beans, stock, and sachet of spices",
            "Bring to a boil and simmer for around 1 hour",
            "Season with salt and pepper and simmer until beans are tender",
            "Remove the sachet of spices",
            "Beans can be strained and used immediately or stored in the liquid",

        ],
    },

}