markets = {
    "home": {
        'location': "Home",
        'distance': 0,
        'notes' : "Home is where the kitchen is",
        'ingredients' : {
            "water": {'price': 0, 'priceUnit': 'ml', 'brand': 'tap', 'size': 1 },
            "stock scraps": {'price': 0, 'priceUnit': 'g', 'brand': 'home', 'size': 1 },
            "basil": {'price': 0.50, 'priceUnit': 'kg', 'brand': 'home', 'size': 1 },
        }
    },
    "save-on": {
        'location': "1403 E King Edward Ave, Vancouver",
        'distance': 4.7,
        'notes' : "",
        'search': "https://www.saveonfoods.com/sm/pickup/rsid/2246/results?q=",
        'ingredients' : {
            "ap flour": {'price': 14.99, 'priceUnit': 'kg', 'brand': 'Western Family', 'size': 10},
            "instant dry yeast": {'price': 7.19, 'priceUnit': 'g', 'brand': 'Fleischmanns', 'size': 113 },
            "salt":  {'price': 13.99, 'priceUnit': 'kg', 'brand': 'Diamond Kosher', 'size': 1.36 },
            "sugar": {'price': 6.99, 'priceUnit': 'kg', 'brand': 'Rogers', 'size': 4 },
            "lg egg": {'price': 4.35, 'priceUnit': 'each', 'brand': 'Western Family', 'size': 12 },
            "olive oil": {'price': 19.29, 'priceUnit': 'ml', 'brand': 'Filippo Berio', 'size': 500 },
            "instant coffee": {'price': 10.39, 'priceUnit': 'g', 'brand': 'Nescafe Rich', 'size': 100 },
            "honey": {'price': 13.99, 'priceUnit': 'kg', 'brand': 'Western Family', 'size': 1 },
            "balsamic vinegar": {'price': 9.89, 'priceUnit': 'ml', 'brand': 'Mazzetti', 'size': 500 },
            "apple cider vinegar": {'price': 12.49, 'priceUnit': 'ml', 'brand': 'Bragg', 'size': 946 },
            "sesame oil": {'price': 5.79, 'priceUnit': 'ml', 'brand': 'Kosa', 'size': 185 },
            "grapeseed oil": {'price': 10.99, 'priceUnit': 'ml', 'brand': 'Western Family', 'size': 750 },
            "sesame seeds": {'price': 3.99, 'priceUnit': 'g', 'brand': 'Western Family', 'size': 145 },
            "peanut butter": {'price': 11.49, 'priceUnit': 'g', 'brand': 'Kraft', 'size': 1000 },
            "mandarin orange": {'price': 4.99, 'priceUnit': 'lb', 'brand': 'Halo', 'size': 2 },
            "white rice": {'price': 17.69, 'priceUnit': 'kg', 'brand': 'YU', 'size': 6 },
            "whole coffee bean": {'price': 16.99, 'priceUnit': 'lb', 'brand': 'Salt Spring Coffee', 'size': 1 },
            "popcorn kernels": {'price': 8.29, 'priceUnit': 'g', 'brand': "Orville Redenbachers", 'size': 850 },
            "nutritional yeast": {'price': 4.99, 'priceUnit': 'g', 'brand': "Red Star", 'size': 100 },
            "cocoa powder": {'price': 13.69, 'priceUnit': 'g', 'brand': "Frys", 'size': 454 },
            "panko": {'price': 5.79, 'priceUnit': 'g', 'brand': "Western Family", 'size': 227 },
            "baking soda": {'price': 2.19, 'priceUnit': 'g', 'brand': "Western Family", 'size': 500 },
            "baking powder": {'price': 8.69, 'priceUnit': 'g', 'brand': 'Magic', 'size': 450 },
            "vanilla extract": {'price': 17.99, 'priceUnit': 'ml', 'brand': 'Bakers Supply', 'size': 100 },
            "golden corn syrup": {'price': 5.19, 'priceUnit': 'ml', 'brand': 'Crown', 'size': 500 },
            "brown sugar": {'price': 4.39, 'priceUnit': 'kg', 'brand': 'Rogers', 'size': 1 },
            "dates": {'price': 7.99, 'priceUnit': 'g', 'brand': 'Western Family', 'size': 640 },
            "rolled oats": {'price': 6.29, 'priceUnit': 'kg', 'brand': 'Rogers', 'size': 1 },
            "walnut pieces": {'price': 2.69, 'priceUnit': 'g', 'brand': 'Bulk', 'size': 100 },
            "dry spaghetti": {'price': 3.29, 'priceUnit': 'g', 'brand': 'Western Family', 'size': 900 },
            "pumpkin seeds": {'price': 2.79, 'priceUnit': 'g', 'brand': 'Bulk', 'size': 100 },
            "raw almonds": {'price': 2.99, 'priceUnit': 'g', 'brand': 'Bulk', 'size': 100 },
            "arborio rice": {'price': 7.99, 'priceUnit': 'g', 'brand': 'SunRice', 'size': 750 },
            "sunflower seeds": {'price': 5.69, 'priceUnit': 'g', 'brand': 'Western Family', 'size': 150 },
            "dry pinto beans": {'price': 4.19, 'priceUnit': 'g', 'brand': 'Western Family', 'size': 450 },
            "dry kidney beans": {'price': 6.29, 'priceUnit': 'g', 'brand': 'Western Family', 'size': 900 },
            "dry red lentils": {'price': 3.69, 'priceUnit': 'lb', 'brand': 'Sundar', 'size': 2 },
            "dry green lentils": {'price': 4.89, 'priceUnit': 'g', 'brand': 'Sundar', 'size': 450 },
            "dry black bean": {'price': 4.19, 'priceUnit': 'g', 'brand': 'Bulk', 'size': 450 },
            "avocado": {'price': 2.49, 'priceUnit': 'each', 'brand': 'Bulk', 'size': 1 },
            "onion": {'price': 0.44, 'priceUnit': 'g', 'brand': 'Bulk', 'size': 100 },
            "fish sauce": {'price': 4.69, 'priceUnit': 'ml', 'brand': 'Kosa', 'size': 750 },
            "canned chickpeas": {'price': 3.99, 'priceUnit': 'ml', 'brand': 'Everland Organic', 'size': 389 },
            "cornmeal": {'price': 5.69, 'priceUnit': 'g', 'brand': 'Bulk', 'size': 680 },
            "canned peas": {'price': 2.19, 'priceUnit': 'ml', 'brand': 'Only Goodness', 'size': 389 },
            "canned crushed tomatoes": {'price': 2.59, 'priceUnit': 'ml', 'brand': 'Western Family', 'size': 796 },
            "canned pineapple": {'price': 3.59, 'priceUnit': 'ml', 'brand': 'Dole', 'size': 398 },
            "instant noodles": {'price': 2.19, 'priceUnit': 'each', 'brand': 'Nong Shim', 'size': 1 },
            "tortilla chips": {'price': 5.79, 'priceUnit': 'g', 'brand': 'Que Pasa', 'size': 350 },
            "tabasco": {'price': 13.69, 'priceUnit': 'ml', 'brand': 'Tabasco', 'size': 350 },
            "molasses": {'price': 6.29, 'priceUnit': 'ml', 'brand': 'Crosby', 'size': 675 },
            "mayonnaise": {'price': 6.79, 'priceUnit': 'ml', 'brand': 'Western Familt', 'size': 890 },
            "extra firm tofu": {'price': 3.99, 'priceUnit': 'g', 'brand': 'Sunrise', 'size': 350 },
            "yellow mustard": {'price': 3.39, 'priceUnit': 'ml', 'brand': 'Frenchs', 'size': 400 },
            "carrot": {'price': 6.99, 'priceUnit': 'lb', 'brand': 'Bulk', 'size': 5 },
            "celery": {'price': 0.77, 'priceUnit': 'g', 'brand': 'Bulk', 'size': 100 },
            "cabbage": {'price': 0.33, 'priceUnit': 'g', 'brand': 'Bulk', 'size': 100 },
            "salted butter": {'price': 8.49, 'priceUnit': 'g', 'brand': 'Western Family', 'size': 454 },
            "garlic": {'price': 6.99, 'priceUnit': 'g', 'brand': 'Bulk', 'size': 1000 },
            "bell pepper": {'price': 8.99, 'priceUnit': 'g', 'brand': 'Windset Farms', 'size': 908 },
            "leek": {'price': 0.99, 'priceUnit': 'g', 'brand': 'Bulk', 'size': 100 },
            "jalapeno": {'price': 1.32, 'priceUnit': 'g', 'brand': 'Bulk', 'size': 100 },
            "canned plum tomato": {'price': 2.56, 'priceUnit': 'ml', 'brand': 'Western Family', 'size': 796 },
            "basil": {'price': 2.79, 'priceUnit': 'g', 'brand': 'Western Family', 'size': 20 },
            "lemon": {'price': 7.49, 'priceUnit': 'lb', 'brand': 'Wonderful', 'size': 2 },
            "cucumber": {'price': 1.99, 'priceUnit': 'each', 'brand': 'Bulk', 'size': 1 },
            "red wine vinegar": {'price': 5.69, 'priceUnit': 'ml', 'brand': 'Western Family', 'size': 500 },
            "black pepper": {'price': 8.69, 'priceUnit': 'g', 'brand': 'Western Family', 'size': 120 },
            "cumin": {'price': 6.59, 'priceUnit': 'g', 'brand': 'Mccormick', 'size': 37 },
            "coriander": {'price': 6.69, 'priceUnit': 'g', 'brand': 'Mccormick', 'size': 28 },
            "cardamom": {'price': 18.99, 'priceUnit': 'g', 'brand': 'Morton & Bassett', 'size': 24 },
            "cinnamon": {'price': 10.49, 'priceUnit': 'g', 'brand': 'Western Family', 'size': 105 },
            "cloves" : {'price': 11.49, 'priceUnit': 'g', 'brand': 'Mccormick', 'size': 26 },  
            "star Anise" : {'price': 11.99, 'priceUnit': 'g', 'brand': 'Morton & Bassett', 'size': 17 },
            "fennel seed" : {'price': 2.69, 'priceUnit': 'g', 'brand': 'Sundar', 'size': 200 },
            "smoked paprika" : {'price': 8.29, 'priceUnit': 'g', 'brand': 'Club House', 'size': 116 },
            "dried thyme" : {'price': 3.69, 'priceUnit': 'g', 'brand': 'Club House', 'size': 11 },
            "cayenne powder" : {'price': 5.69, 'priceUnit': 'g', 'brand': 'Western Family', 'size': 97 },
            "garlic powder" : {'price': 8.69, 'priceUnit': 'g', 'brand': 'Western Family', 'size': 155 },
            "onion powder" : {'price': 8.69, 'priceUnit': 'g', 'brand': 'Western Family', 'size': 155 },
            "chives" : {'price': 2.79, 'priceUnit': 'g', 'brand': 'Western Family', 'size': 20 },
            "cilantro" : {'price': 2.79, 'priceUnit': 'bunch', 'brand': 'Bulk', 'size': 1 },
            "italian parsley" : {'price': 2.49, 'priceUnit': 'bunch', 'brand': 'Bulk', 'size': 1 },
            "parsley" : {'price': 2.49, 'priceUnit': 'bunch', 'brand': 'Bulk', 'size': 1 },
            "tarragon" : {'price': 2.79, 'priceUnit': 'g', 'brand': 'Bulk', 'size': 20 },
            "thyme" : {'price': 2.79, 'priceUnit': 'bunch', 'brand': 'Bulk', 'size': 20 },
            "mustard seed" : {'price': 2.19, 'priceUnit': 'g', 'brand': 'Teja', 'size': 100 },
            "allspice" : {'price': 6.59, 'priceUnit': 'g', 'brand': 'Mccormick', 'size': 34 },
            "caraway" : {'price': 6.69, 'priceUnit': 'g', 'brand': 'Sundar', 'size': 38 },
            "italian seasoning" : {'price': 3.99, 'priceUnit': 'g', 'brand': 'Western Family', 'size': 37 },
            "dried dill": {'price': 3.69, 'priceUnit': 'g', 'brand': 'Club House', 'size': 12 },
            "chili powder" : {'price': 6.29, 'priceUnit': 'g', 'brand': 'Western Family', 'size': 155 },
            "anise seed" : {'price': 6.59, 'priceUnit': 'g', 'brand': 'Western Family', 'size': 38 },
            "celery seed" : {'price': 6.69, 'priceUnit': 'g', 'brand': 'Western Family', 'size': 36 },
            "celery salt" : {'price': 8.69, 'priceUnit': 'g', 'brand': 'Club House', 'size': 190 },
            "dried basil" : {'price': 11.99, 'priceUnit': 'g', 'brand': 'Morton & Bassett', 'size': 19 },
            "curry powder" : {'price': 5.69, 'priceUnit': 'g', 'brand': 'Western Family', 'size': 130 },
            "dried rosemary" : {'price': 11.99, 'priceUnit': 'g', 'brand': 'Club House', 'size': 19 },
            "rosemary": {'price': 2.79, 'priceUnit': 'g', 'brand': 'Western Family', 'size': 20 },
            "ground tumeric" : {'price': 3.29, 'priceUnit': 'g', 'brand': 'Western Family', 'size': 200 },
            "ground ginger" : {'price': 6.29, 'priceUnit': 'g', 'brand': 'Western Family', 'size': 105 },
            "dried oregano" : {'price': 3.69, 'priceUnit': 'g', 'brand': 'Club House', 'size': 11 },
            "lime" : {'price': 6.99, 'priceUnit': 'g', 'brand': 'Bulk', 'size': 454 },
            "ginger" : {'price': 0.77, 'priceUnit': 'g', 'brand': 'Bulk', 'size': 100 },
            "mango" : {'price': 3.99, 'priceUnit': 'each', 'brand': 'Bulk', 'size': 1 },
            "russet potato" : {'price': 0.99, 'priceUnit': 'g', 'brand': 'Bulk', 'size': 100 },
            "vegetable oil" : {'price': 12.99, 'priceUnit': 'l', 'brand': 'Western Family', 'size': 3 },
            "green onion" : {'price': 2.99, 'priceUnit': 'bunch', 'brand': 'Bulk', 'size': 1 },

        }
    },
    "safeway": {
        'location': "990 W King Edward Ave, Vancouver",
        'distance': 0.23,
        'notes' : "This is the closest market to my house.",
        'search': "https://voila.ca/search?q=",
        'ingredients' : {
            "ap flour": {'price': 15.79, 'priceUnit': 'kg', 'brand': 'Compliments', 'size': 10 },
            "instant dry yeast": {'price': 6.79, 'priceUnit': 'g', 'brand': 'Fleischmanns', 'size': 113 },
            "sugar": {'price': 6.99, 'priceUnit': 'kg', 'brand': 'Rogers', 'size': 4 },
            "lg egg": {'price': 4.19, 'priceUnit': 'each', 'brand': 'Compliments', 'size': 12 },
            "olive oil": {'price': 19.29, 'priceUnit': 'ml', 'brand': 'Bertolli', 'size': 500 },
            "instant coffee": {'price': 9.99, 'priceUnit': 'g', 'brand': 'Nescafe Rich', 'size': 170 },
            "honey": {'price': 13.99, 'priceUnit': 'kg', 'brand': 'Compliments', 'size': 1 },
            "balsamic vinegar": {'price': 6.49, 'priceUnit': 'ml', 'brand': 'Bertolli', 'size': 500 },
            "apple cider vinegar": {'price': 11.49, 'priceUnit': 'ml', 'brand': 'Bragg', 'size': 946 },
            "sesame oil": {'price': 3.99, 'priceUnit': 'ml', 'brand': 'Lee Kum Kee', 'size': 207 },
            "grapeseed oil": {'price': 15.29, 'priceUnit': 'ml', 'brand': 'Basso Pure', 'size': 1000 },
            "sesame seeds": {'price': 2.79, 'priceUnit': 'g', 'brand': 'Chalo', 'size': 200 },
            "peanut butter": {'price': 6.79, 'priceUnit': 'g', 'brand': 'Compliments Naturally', 'size': 1000 },
            "mandarin orange": {'price': 7.99, 'priceUnit': 'kg', 'brand': 'Halo', 'size': 1.81 },
            "white rice": {'price': 11.88, 'priceUnit': 'kg', 'brand': 'Yamay', 'size': 8},
            "whole coffee bean": {'price': 9.99, 'priceUnit': 'g', 'brand': 'Ethical Addictions', 'size': 340 },
            "popcorn kernels": {'price': 7.79, 'priceUnit': 'g', 'brand': "Orville Redenbachers", 'size': 850 },
            "nutritional yeast": {'price': 11.29, 'priceUnit': 'g', 'brand': "Bobs Red Mill", 'size': 142 },
            "cocoa powder": {'price': 12.99, 'priceUnit': 'g', 'brand': "Frys", 'size': 454 },
            "rye flour": {'price': 6.79, 'priceUnit': 'kg', 'brand': 'Compliments', 'size': 1 },
            "vital wheat gluten": {'price': 13.79, 'priceUnit': 'g', 'brand': 'Bobs Red Mill', 'size': 567 },
            "panko": {'price': 3.99, 'priceUnit': 'g', 'brand': "Martelli", 'size': 227 },
            "maldon salt": {'price': 9.99, 'priceUnit': 'g', 'brand': "Maldon", 'size': 240 },
            "baking soda": {'price': 1.99, 'priceUnit': 'g', 'brand': "Compliments", 'size': 500 },
            "baking powder": {'price': 7.99, 'priceUnit': 'g', 'brand': 'Magic', 'size': 450 },
            "vanilla extract": {'price': 12.99, 'priceUnit': 'ml', 'brand': 'Bakers Supply', 'size': 100 },
            "golden corn syrup": {'price': 4.99, 'priceUnit': 'ml', 'brand': 'Crown', 'size': 500 },
            "brown sugar": {'price': 3.29, 'priceUnit': 'kg', 'brand': 'Rogers', 'size': 1 },
            "dates": {'price': 7.49, 'priceUnit': 'g', 'brand': 'Compliments', 'size': 600 },
            "mango puree": {'price': 5.49, 'priceUnit': 'g', 'brand': 'Compliments', 'size': 850 },
            "corn grits": {'price': 4.99, 'priceUnit': 'g', 'brand': 'Compliments', 'size': 680 },
            "rolled oats": {'price': 4.79, 'priceUnit': 'kg', 'brand': 'Compliments', 'size': 1 },
            "walnut pieces": {'price': 16.79, 'priceUnit': 'g', 'brand': 'Compliments', 'size': 750 },
            "dry spaghetti": {'price': 3.19, 'priceUnit': 'g', 'brand': 'Compliments', 'size': 900 },
            "pumpkin seeds": {'price': 6.29, 'priceUnit': 'g', 'brand': 'Compliments', 'size': 300 },
            "raw almonds": {'price': 14.99, 'priceUnit': 'g', 'brand': 'Compliments', 'size': 907 },
            "arborio rice": {'price': 7.99, 'priceUnit': 'g', 'brand': 'Rice Select', 'size': 907 },
            "sunflower seeds": {'price': 1.09, 'priceUnit': 'g', 'brand': 'Compliments', 'size': 100 },
            "dry pinto beans": {'price': 3.99 , 'priceUnit': 'g', 'brand': 'Compliments', 'size': 900 },
            "dry kidney beans": {'price': 4.49, 'priceUnit': 'g', 'brand': 'Compliments', 'size': 900 },
            "dry red lentils": {'price': 6.99, 'priceUnit': 'kg', 'brand': 'Compliments', 'size': 1.81 },
            "dry green lentils": {'price': 2.19, 'priceUnit': 'g', 'brand': 'Compliments', 'size': 450 },
            "dry bean soup mix": {'price': 6.79, 'priceUnit': 'g', 'brand': 'Bobs Red Mill', 'size': 822 },
            "dry black eyed beans": {'price': 8.99, 'priceUnit': 'g', 'brand': 'Compliments', 'size': 1810 },
            "dry black beans": {'price': 10.99, 'priceUnit': 'g', 'brand': 'Compliments', 'size': 1810 },
            "avocado": {'price': 2.49, 'priceUnit': 'each', 'brand': 'Hass', 'size': 1 },
            "onion": {'price': 2.99, 'priceUnit': 'g', 'brand': 'Netted', 'size': 907 },
            "fish sauce": {'price': 4.29, 'priceUnit': 'ml', 'brand': 'Marca Pina', 'size': 1000 },
            "canned chickpeas": {'price': 2.29, 'priceUnit': 'ml', 'brand': 'Compliments', 'size': 540 },
            "cornmeal": {'price': 6.79, 'priceUnit': 'kg', 'brand': 'Grace', 'size': 2 },
            "chickpea flour": {'price': 7.49, 'priceUnit': 'g', 'brand': 'Good Eats', 'size': 500 },
            "canned peas": {'price': 1.99, 'priceUnit': 'ml', 'brand': 'Compliments', 'size': 398 },
            "dried cherries": {'price': 6.29, 'priceUnit': 'g', 'brand': 'Compliments', 'size': 170 },
            "canned crushed tomatoes": {'price': 2.29, 'priceUnit': 'ml', 'brand': 'Compliments', 'size': 796 },
            "canned pineapple": {'price': 2.69, 'priceUnit': 'ml', 'brand': 'Compliments', 'size': 398 },
            "instant noodles": {'price': 6.99, 'priceUnit': 'each', 'brand': 'Nong Shim', 'size': 4 },
            "tortilla chips": {'price': 5.99, 'priceUnit': 'g', 'brand': 'Tostitos', 'size': 455 },
            "tabasco": {'price': 12.99, 'priceUnit': 'ml', 'brand': 'Tabasco', 'size': 350 },
            "molasses": {'price': 4.99, 'priceUnit': 'ml', 'brand': 'Compliments', 'size': 675 },
            "mayonnaise": {'price': 6.79, 'priceUnit': 'ml', 'brand': 'Hellmanns', 'size': 890 },
            "extra firm tofu": {'price': 3.49, 'priceUnit': 'g', 'brand': 'Sunrise', 'size': 350 },
            "yellow mustard": {'price': 2.79, 'priceUnit': 'ml', 'brand': 'Frenchs', 'size': 400 },
            "carrot": {'price': 4.49, 'priceUnit': 'g', 'brand': 'Bulk', 'size': 1360 },
            "celery": {'price': 3.99, 'priceUnit': 'g', 'brand': 'Bunch', 'size': 375 },
            "cabbage": {'price': 4.92, 'priceUnit': 'kg', 'brand': 'Bulk', 'size': 1.5 },
            "salted butter": {'price': 5.99, 'priceUnit': 'g', 'brand': 'Compliments', 'size': 454 },
            "garlic": {'price': 1.79, 'priceUnit': 'each', 'brand': 'Bulk', 'size': 5 },
            "bell pepper": {'price': 8.99, 'priceUnit': 'g', 'brand': 'NatureFresh', 'size': 908 },
            "leek": {'price': 0.99, 'priceUnit': 'g', 'brand': 'Bulk', 'size': 100 },
            "jalapeno": {'price': 1.32, 'priceUnit': 'g', 'brand': 'Bulk', 'size': 100 },
            "plum tomato": {'price': 6.19, 'priceUnit': 'kg', 'brand': 'Bulk', 'size': 1 },
            "canned plum tomato": {'price': 2.99, 'priceUnit': 'ml', 'brand': 'Aylmer', 'size': 796 },
            "basil": {'price': 2.79, 'priceUnit': 'g', 'brand': 'Compliments', 'size': 20 },
            "lemon": {'price': 6.49, 'priceUnit': 'g', 'brand': 'Copliments', 'size': 907 },
            "cucumber": {'price': 1.99, 'priceUnit': 'each', 'brand': 'Bulk', 'size': 1 },
            "red wine vinegar": {'price': 5.49, 'priceUnit': 'ml', 'brand': 'Compliments', 'size': 500 },
            "black pepper": {'price': 5.79, 'priceUnit': 'g', 'brand': 'Compliments', 'size': 120 },
            "cumin": {'price': 5.49, 'priceUnit': 'g', 'brand': 'Chalo', 'size': 400 },
            "coriander": {'price': 2.79, 'priceUnit': 'g', 'brand': 'Chalo', 'size': 200 },
            "cardamom": {'price': 2.99, 'priceUnit': 'g', 'brand': 'Chalo', 'size': 50 },
            "cinnamon": {'price': 6.79, 'priceUnit': 'g', 'brand': 'Compliments', 'size': 105 },
            "cloves" : {'price': 3.99, 'priceUnit': 'g', 'brand': 'Chalo', 'size': 100 },
            "nutmeg" : {'price': 3.69, 'priceUnit': 'g', 'brand': 'Chalo', 'size': 50 },
            "bay leaf" : {'price': 1.79, 'priceUnit': 'g', 'brand': 'Chalo', 'size': 50 },
            "star anise" : {'price': 4.69, 'priceUnit': 'g', 'brand': 'Chalo', 'size': 100 },
            "fennel seed" : {'price': 2.79, 'priceUnit': 'g', 'brand': 'Chalo', 'size': 200 },
            "smoked paprika" : {'price': 4.29, 'priceUnit': 'g', 'brand': 'Chalo', 'size': 400 },
            "sweet paprika": {'price': 4.29, 'priceUnit': 'g', 'brand': 'Salem', 'size': 200 },
            "mustard powder": {'price': 3.69, 'priceUnit': 'g', 'brand': 'Compliments', 'size': 95 },
            "dried thyme": {'price': 2.49, 'priceUnit': 'g', 'brand': 'Compliments', 'size': 45 },
            "dried orgeno": {'price': 3.29, 'priceUnit': 'g', 'brand': 'Compliments', 'size': 32 },
            "cayenne powder": {'price': 3.99, 'priceUnit': 'g', 'brand': 'Chalo', 'size': 400 },
            "garlic powder": {'price': 4.29, 'priceUnit': 'g', 'brand': 'Chalo', 'size': 400 },
            "onion powder": {'price': 2.99, 'priceUnit': 'g', 'brand': 'Chalo', 'size': 200 },
            "chives" : {'price': 2.99, 'priceUnit': 'g', 'brand': 'Compliments', 'size': 20 },
            "cilantro" : {'price': 2.49, 'priceUnit': 'bunch', 'brand': 'Bulk', 'size': 1 },
            "italian parsley" : {'price': 2.49, 'priceUnit': 'bunch', 'brand': 'Bulk', 'size': 1 },
            "parsley" : {'price': 2.49, 'priceUnit': 'bunch', 'brand': 'Bulk', 'size': 1 },
            "tarragon" : {'price': 2.99, 'priceUnit': 'g', 'brand': 'Compliments', 'size': 28 },
            "thyme" : {'price': 2.99, 'priceUnit': 'g', 'brand': 'Compliments', 'size': 28 },
            "sumac" : {'price': 6.49, 'priceUnit': 'g', 'brand': 'Compliments', 'size': 340 },
            "allspice" : {'price': 5.99, 'priceUnit': 'g', 'brand': 'Teja', 'size': 100 },
            "caraway" : {'price': 4.39, 'priceUnit': 'g', 'brand': 'Chalo', 'size': 100 },
            "italian seasoning" : {'price': 3.29, 'priceUnit': 'g', 'brand': 'Compliments', 'size': 37 },
            "dried dill": {'price': 6.99, 'priceUnit': 'g', 'brand': 'Compliments', 'size': 10 },
            "dried lime leaves": {'price': 4.49, 'priceUnit': 'oz', 'brand': 'Compliments', 'size': 2 },
            "chili powder" : {'price': 3.79, 'priceUnit': 'g', 'brand': 'Chalo', 'size': 155 },
            "anise seed" : {'price': 2.79, 'priceUnit': 'g', 'brand': 'Chalo', 'size': 100 },
            "celery seed" : {'price': 4.49, 'priceUnit': 'g', 'brand': 'Chalo', 'size': 100 },
            "celery salt" : {'price': 4.19, 'priceUnit': 'g', 'brand': 'Club House', 'size': 206 },
            "dried basil" : {'price': 3.19, 'priceUnit': 'g', 'brand': 'Compliments', 'size': 42 },
            "curry powder" : {'price': 4.19, 'priceUnit': 'g', 'brand': 'Compliments', 'size': 130 },
            "zaatar" : {'price': 5.99, 'priceUnit': 'g', 'brand': 'Compliments', 'size': 37 },
            "dried rosemary" : {'price': 3.69, 'priceUnit': 'g', 'brand': 'Compliments', 'size': 47 },
            "rosemary": {'price': 2.99, 'priceUnit': 'g', 'brand': 'Compliments', 'size': 28 },
            "ground tumeric" : {'price': 3.29, 'priceUnit': 'g', 'brand': 'Chalo', 'size': 400 },
            "ground ginger" : {'price': 2.99, 'priceUnit': 'g', 'brand': 'Chalo', 'size': 200 },
            "dried oregano" : {'price': 3.29, 'priceUnit': 'g', 'brand': 'Compliments', 'size': 32 },
            "lime" : {'price': 4.49, 'priceUnit': 'g', 'brand': 'Bulk', 'size': 454 },
            "ginger" : {'price': 0.77, 'priceUnit': 'g', 'brand': 'Bulk', 'size': 100 },
            "mango" : {'price': 3.99, 'priceUnit': 'each', 'brand': 'Bulk', 'size': 1 },
            "russet potato" : {'price': 0.99, 'priceUnit': 'g', 'brand': 'Bulk', 'size': 2270 },
            "matzo meal" : {'price': 4.99, 'priceUnit': 'g', 'brand': 'Compliments', 'size': 140 },
            "dried chickpeas" : {'price': 3.99, 'priceUnit': 'g', 'brand': 'Compliments', 'size': 900 },
            "dried fava beans" : {'price': 8.29, 'priceUnit': 'g', 'brand': 'Clic', 'size': 907 },
            "vegetable oil" : {'price': 12.99, 'priceUnit': 'l', 'brand': 'Compliments', 'size': 3 },
            "dried navy beans" : {'price': 4.19, 'priceUnit': 'g', 'brand': 'Compliments', 'size': 900 },
            "green onion" : {'price': 2.29, 'priceUnit': 'bunch', 'brand': 'Bulk', 'size': 1 },
        }
    },
    "costco": {
        'location': "605 Expo Blvd, Vancouver",
        'distance': 5.6,
        'notes' : "Need to buy in bulk.",
        'search': "https://www.costco.ca/s?langId=-24&keyword=",
        'ingredients' : {
            "ap flour": {'price': 9.99, 'priceUnit': 'kg', 'brand': 'Rogers',       'size': 10 },
            "sugar": {'price': 20.99, 'priceUnit': 'kg', 'brand': 'Rogers', 'size': 10 },
            "olive oil": {'price': 44.99, 'priceUnit': 'ml', 'brand': 'Terra Delyssa', 'size': 500 },
            "instant coffee": {'price': 15.99, 'priceUnit': 'g', 'brand': 'Nescafe Rich', 'size': 475 },
            "grapeseed oil": {'price': 22.99, 'priceUnit': 'l', 'brand': 'Ottavio', 'size': 3 },
            "panko": {'price': 14.99, 'priceUnit': 'g', 'brand': "Kikkoman", 'size': 1360 },
            "baking soda": {'price': 7.99, 'priceUnit': 'g', 'brand': "Arm & Hammer", 'size': 2000 },
            "baking powder": {'price': 39.99, 'priceUnit': 'kg', 'brand': 'Magic', 'size': 2.5 },
            "dates": {'price': 11.99, 'priceUnit': 'g', 'brand': 'Terra Delyssa', 'size': 1250 },
            "rolled oats": {'price': 12.49, 'priceUnit': 'kg', 'brand': 'Quaker', 'size': 2.27 },
            "walnut pieces": {'price': 19.99, 'priceUnit': 'kg', 'brand': 'Kirkland', 'size': 2 },
            "dry spaghetti": {'price': 12.99, 'priceUnit': 'g', 'brand': 'Griss', 'size': 4000 },
            "pumpkin seeds": {'price': 21.99, 'priceUnit': 'kg', 'brand': 'Kirkland', 'size': 2 },
            "raw almonds": {'price': 34.99, 'priceUnit': 'kg', 'brand': 'Kirkland', 'size': 3 },
            "arborio rice": {'price': 22.99, 'priceUnit': 'kg', 'brand': 'Ristoris', 'size': 5 },
            "sunflower seeds": {'price': 9.99, 'priceUnit': 'kg', 'brand': 'Yupik', 'size': 2 },
            "dry pinto beans": {'price': 29.99 , 'priceUnit': 'kg', 'brand': 'Clic', 'size': 10 },
            "dry pinto beans": {'price': 32.99 , 'priceUnit': 'kg', 'brand': 'Clic', 'size': 10 },
            "dry red lentils": {'price': 27.99, 'priceUnit': 'kg', 'brand': 'Clic', 'size': 10 },
            "dry green lentils": {'price': 28.99, 'priceUnit': 'kg', 'brand': 'Clic', 'size': 10 },
            "mayonnaise": {'price': 11.99, 'priceUnit': 'ml', 'brand': 'Kirkland', 'size': 1900 },
            "canned plum tomato": {'price': 11.99, 'priceUnit': 'l', 'brand': 'La San Marzano', 'size': 2.84 },
            "vegetable oil": {'price': 14.99, 'priceUnit': 'l', 'brand': 'Saporito', 'size': 5   },
        }
    },
    "london drugs": {
        "location": "525 W Broadway, Vancouver",
        "distance": 2.4,
        "notes": "This is the closest market to my work.",
        "search": "https://www.londondrugs.com/search/?q=",
        "ingredients": {
            "panko": {'price': 4.99, 'priceUnit': 'g', 'brand': "Kikkoman", 'size': 227 },
            "baking soda": {'price': 2.99, 'priceUnit': 'g', 'brand': "Arm & Hammer", 'size': 500 },
            "vanilla extract": {'price': 15.99, 'priceUnit': 'ml', 'brand': 'Bakers Supply', 'size': 100 },
            "rolled oats": {'price': 5.99, 'priceUnit': 'kg', 'brand': 'Dan-D', 'size': 1 },
            "walnut pieces": {'price': 9.99, 'priceUnit': 'g', 'brand': 'Today by London Drugs', 'size': 454 },
            "dry spaghetti": {'price': 3.99, 'priceUnit': 'g', 'brand': 'De Cecco', 'size': 454 },
            "pumpkin seeds": {'price': 6.99, 'priceUnit': 'g', 'brand': 'Today by London Drugs', 'size': 350 },
            "raw almonds": {'price': 13.99, 'priceUnit': 'g', 'brand': 'Today by London Drugs', 'size': 600 },
            "sunflower seeds": {'price': 6.99, 'priceUnit': 'g', 'brand': 'Today by London Drugs', 'size': 400 },
            "canned chickpeas": {'price': 2.99, 'priceUnit': 'ml', 'brand': 'Primo', 'size': 540 },
            "tortilla chips": {'price': 4.99, 'priceUnit': 'g', 'brand': 'Que Pasa', 'size': 350 },
        }
    },
    "t&t":{
        "location": "179 Keefer Pl, Vancouver",
        "distance": 4.5,
        "notes": "This is the closest market to my work.",
        "search": "https://www.tntsupermarket.com/search?q=",
        "ingredients": {
            "dry shitake mushrooms": {'price': 9.89, 'priceUnit': 'g', 'brand': 'Dashanhe', 'size': 200 },
            "onion": {'price': 2.49, 'priceUnit': 'g', 'brand': 'Netted', 'size': 907 },
            "fish sauce": {'price': 3.99, 'priceUnit': 'ml', 'brand': 'Marca Pina', 'size': 700 },
            "instant noodles": {'price': 8.57, 'priceUnit': 'each', 'brand': 'Nong Shim', 'size': 5 },
            "carrot": {'price': 2.49, 'priceUnit': 'lb', 'brand': 'Bulk', 'size': 2 },
            "cabbage": {'price': 1, 'priceUnit': 'lb', 'brand': 'Bulk', 'size': 1 },
            "bell pepper": {'price': 4.67, 'priceUnit': 'lb', 'brand': 'Bulk', 'size': 1 },
            "jalapeno": {'price': 3.99, 'priceUnit': 'lb', 'brand': 'Bulk', 'size': 1 },
            "lemon": {'price': 0.89, 'priceUnit': 'each', 'brand': 'Bulk', 'size': 1 },
            "cumin": {'price': 2.29, 'priceUnit': 'g', 'brand': 'Bulk', 'size': 55 },
            "star anise": {'price': 3.29, 'priceUnit': 'g', 'brand': 'Youjia', 'size': 20 },
            "parsley": {'price': 1.29, 'priceUnit': 'bunch', 'brand': 'Bulk', 'size': 1 },
            "vegetable oil": {'price': 9.99, 'priceUnit': 'l', 'brand': 'No Name', 'size': 3 },
        }
    }
}
